"""The pilot's temporal blind spot, stated on the report instead of hidden in a footnote.

## What the blind spot is

Every audit prices against one catalog edition, and that edition is `goae_current` — the only
edition in `data/catalogs/` that holds real numbers. The historical editions beside it are
synthetic fixtures generated by `scripts/make_temporal_fixtures.py`, and `data/catalogs/README.md`
is explicit that only `goae_current` may price a real invoice. Temporal routing *exists* as a
mechanism (`Settings.catalog_dir_for`); what does not exist yet is anything real to route to.

So an invoice for a treatment in 2020 is audited against the 2026 fee schedule. For most positions
that changes nothing — the GOÄ's § 5 factor bands and the great majority of Ziffern have not
moved — but for the ones it does change, the audit is measuring the invoice against a rule that
did not apply on the day of treatment. A finding produced that way is not wrong arithmetic; it is
arithmetic against the wrong year, which is harder to notice and worse to act on.

## Why this is a warning and not a refusal

Two reasons, and the second is the one that decided it.

**A refusal would be a worse answer than the audit.** Most of a two-year-old invoice is still
checked correctly, and a practice that uploads one and gets a `422` learns nothing at all. The
warning costs them one paragraph and leaves them with a report.

**We cannot tell which positions are actually affected.** Naming this a hard error would imply we
know the audit is wrong, and we do not — we know we cannot prove it is right. That is the same
distinction `unconfirmed` draws in the money buckets, and it gets the same treatment here: say what
we could not check, do not dress it up as a defect in someone's invoice.

The consequence for callers is a guarantee: nothing in this module can change a status code, a
verdict, a bucket or a euro. It reads dates and returns strings.

## Reading the dates

`<datum>` is `xs:date` in the ADL schema, so `YYYY-MM-DD` is what conforming exports carry.
Real PVS exports are the reason `PADNEXT_SCHEMA_POLICY=warn` exists, so `DD.MM.YYYY` and `YYYYMMDD`
are accepted too — a date this module cannot parse is simply not a date it will judge, and an
unreadable one is never reported as old. Silence here is always the safe direction: the check can
fail to warn, it can never invent one.

The delivery's age is its **newest** position date. An invoice is as old as its most recent
treatment; taking the oldest would flag a current invoice that happens to carry one carried-over
line from the previous year, and a warning that fires on normal invoices is a warning nobody reads.
"""

from __future__ import annotations

from datetime import date, datetime

from app.config import Settings
from app.schemas.padnext import PadnextPosition

#: The wording that reaches a practice. A constant, not a literal at the call site, because it is
#: the sentence that describes what this product cannot do yet — and two copies of it would
#: eventually be one copy and one paraphrase that promises something different.
#:
#: It says three things in this order, deliberately: what is true of *this* invoice, what the
#: engine did about it, and what follows for the reader. It does not apologise and it does not
#: suggest the result is unusable, because neither is accurate.
TEMPORAL_SCOPE_WARNING = (
    "Das Leistungsdatum dieser Abrechnung liegt mehr als 12 Monate zurück. Da diese Engine den "
    "aktuellen GOÄ-Katalog verwendet, können historische Regelabweichungen nicht erkannt werden."
)

#: `xs:date` first, because that is what the schema mandates and what a conforming export carries.
#: The other two are for real PVS exports under `PADNEXT_SCHEMA_POLICY=warn`.
_DATE_FORMATS = ("%Y-%m-%d", "%d.%m.%Y", "%Y%m%d")


def parse_service_date(raw: str | None) -> date | None:
    """One `<datum>` as a date, or `None` if it is absent or in no format we recognise.

    `None` rather than an exception on purpose: a date we cannot read must produce no warning at
    all. The delivery's malformed fields are already reported by the reader and by the schema
    check; re-reporting one here as "this invoice is old" would be a false statement about it.
    """
    text = (raw or "").strip()
    if not text:
        return None
    for fmt in _DATE_FORMATS:
        try:
            return datetime.strptime(text, fmt).date()
        except ValueError:
            continue
    return None


def latest_service_date(positions: list[PadnextPosition]) -> date | None:
    """The newest readable `<datum>` across the positions, or `None` if none is readable.

    See the module docstring for why this is a maximum and not a minimum.
    """
    dates = [d for d in (parse_service_date(p.datum) for p in positions) if d is not None]
    return max(dates) if dates else None


def temporal_scope_warnings(
    positions: list[PadnextPosition],
    *,
    settings: Settings,
    today: date | None = None,
) -> tuple[list[str], bool, str]:
    """`(warnings, checked, latest_iso)` for one delivery.

    `checked` is `False` when the limit is `0` (switched off) or when no position carried a
    readable date — which is why it is returned separately. An empty `warnings` list means "nothing
    to flag" only when `checked` is `True`; otherwise it means the question was never asked, the
    same distinction `schema_policy` draws for `schema_warnings`.

    `today` is injectable so the suite can assert on a fixed date rather than on one that will be
    wrong next year — the age of the bundled fixtures moves every day this project is not touched.
    """
    limit_days = settings.pilot_max_invoice_age_days
    if limit_days <= 0:
        return [], False, ""

    newest = latest_service_date(positions)
    if newest is None:
        return [], False, ""

    reference = today or date.today()
    # A future date is not "young"; it is a different defect, and one this module does not own.
    # Comparing on the signed difference means it simply does not fire, rather than firing on the
    # negative age it would otherwise compute.
    age_days = (reference - newest).days
    warnings = [TEMPORAL_SCOPE_WARNING] if age_days > limit_days else []
    return warnings, True, newest.isoformat()


__all__ = [
    "TEMPORAL_SCOPE_WARNING",
    "latest_service_date",
    "parse_service_date",
    "temporal_scope_warnings",
]
