/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Provenance and coverage — deliberately not the full 2000-entry dump.
         *
         *     The warnings are not decoration: rule coverage is `partial`, most exclusion rules were
         *     machine-extracted and are unverified, and no Zielleistung pairs are loaded at all. Publishing
         *     that is the difference between a defensible tool and one that overclaims.
         */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/ziffer/{ziffer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Ziffer */
        get: operations["catalog_ziffer_api_v1_catalog_ziffer__ziffer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/padnext/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Padnext Audit
         * @description Audit a PADnext delivery against the GOÄ rules.
         *
         *     The body is the file itself, not a JSON wrapper or a multipart upload: either a `.padx`
         *     container (a ZIP, sniffed by magic bytes) or a bare `*_padx.xml` payload. Taking raw bytes
         *     avoids a `python-multipart` dependency for what is one file per request.
         *
         *     A delivery flagged as production data is refused with 422 — see `app.padnext.audit` and
         *     `docs/compliance/PRIVATE_DATA_WARNING.md`.
         */
        post: operations["padnext_audit_api_v1_padnext_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/padnext/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Padnext Batch
         * @description Accept many PADnext deliveries and audit them in the background.
         *
         *     Returns `202` with a `batch_id` immediately; the audit itself has not started. Poll
         *     `GET /api/v1/padnext/batch/{batch_id}` for progress, and read `aggregate_summary` once the
         *     status is `COMPLETED`.
         *
         *     Multipart rather than raw bytes, unlike the single-file endpoint: many files in one request is
         *     what multipart is for, and there is no way to delimit them in a raw body. That is why the
         *     engine now depends on `python-multipart`.
         *
         *     A delivery flagged as production data is refused per file, not per batch — the file is marked
         *     `FAILED` with the reason and the rest of the batch proceeds. See
         *     `docs/compliance/PRIVATE_DATA_WARNING.md`.
         */
        post: operations["padnext_batch_api_v1_padnext_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/padnext/batch/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Padnext Batch Status
         * @description The batch's progress, and its result once it is done.
         *
         *     While the job runs, `files` carries each delivery's status and no report — a two-second poll
         *     over a hundred files must not ship a hundred full audit reports per tick. Once the status is
         *     terminal, every completed file's `report` is the same `PadnextAuditReport` the single-file
         *     endpoint would have returned, and `aggregate_summary` holds the roll-up.
         *
         *     `files` arrives sorted by `confirmed_wrong_eur` descending — riskiest first. Sorted here rather
         *     than in the client because the amounts are exact decimal strings that a JavaScript client must
         *     not parse back into numbers.
         */
        get: operations["padnext_batch_status_api_v1_padnext_batch__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/padnext/batch/{batch_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Padnext Batch Export
         * @description Download a completed batch as CSVs, for a billing centre.
         *
         *     Only a `COMPLETED` batch can be exported. A running one would produce totals that are a
         *     snapshot of an unidentifiable moment, and a `FAILED` one has no roll-up at all — both are
         *     `409` rather than a file with a caveat attached, because a caveat does not survive being
         *     opened in a spreadsheet three weeks later.
         *
         *     Read-only: unlike the proposal export this changes no status and writes no audit row, so the
         *     same archive can be downloaded repeatedly and is byte-identical each time. See
         *     `app.services.batch_audit.export_batch` for why the two exports differ on that.
         *
         *     CSV rather than JSON because the reader is a Rechnungsprüfer with a spreadsheet. The archive
         *     carries a `README.txt` stating that `unconfirmed` is the boundary of this engine's rule
         *     coverage and not a finding against the practice — a CSV outlives the screen it came from, and
         *     that sentence has to travel with the numbers.
         */
        post: operations["padnext_batch_export_api_v1_padnext_batch__batch_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_v1_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_v1_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Accept a draft. `approved_by` is required — an unattributed approval is not one.
         */
        post: operations["approve_api_v1_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Proposal
         * @description Export an approved proposal, and record that it left the system.
         *
         *     Only reachable from `APPROVED`; anything else is a `409`. The transition to `EXPORTED` is
         *     terminal, so a proposal can be exported exactly once — which is the point, since the export is
         *     the record of a decision rather than a report that can be regenerated on a whim.
         *
         *     `exported_by` is required. It is written to the `EXPORTED` audit event and into the document
         *     itself, and it is recorded rather than verified: this service authenticates nobody.
         *
         *     The response body is the `ProposalExport` document with a `Content-Disposition: attachment`
         *     header. It is served as a `Response` rather than returned as a model so the header and the
         *     exact bytes are ours — a browser must be able to save this file, and the JSON is
         *     pretty-printed because a human opening it in an editor is a first-class use.
         */
        post: operations["export_proposal_api_v1_proposals__proposal_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Refuse a draft, with a reason. Terminal: a rejected draft is not re-decided, it is re-run.
         */
        post: operations["reject_api_v1_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Rule Coverage
         * @description How much of the rule set is verified, right now, reviews included.
         *
         *     The same object every solve and audit carries, computed from the store the engine is actually
         *     holding — so a progress bar built from it cannot disagree with what the next audit enforces.
         */
        get: operations["rule_coverage_api_v1_rules_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Queue
         * @description Rules that are unverified in the CSVs and that nobody has decided about yet.
         *
         *     A rule leaves this queue when a review marks it `VERIFIED` or `REJECTED`. `PENDING` does not
         *     remove it, deliberately: a reviewer parking a rule they could not decide has not made it any
         *     safer, and a queue that hid parked rules would let the backlog quietly stop being the backlog.
         *
         *     Sorted by rule type and then by id, so the list is stable across polls — a queue that reordered
         *     under a reviewer between reading a rule and clicking Verify would be worse than a slow one.
         */
        get: operations["review_queue_api_v1_rules_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Rule
         * @description Record a verdict on one rule and merge it into the running engine.
         *
         *     `VERIFIED` makes the rule enforce exactly like a hand-curated one, which moves euros out of
         *     `unconfirmed` in every subsequent audit. `REJECTED` means a human read the machine-extracted
         *     rule and refused it: it never enforces again, not even under `UNVERIFIED_RULE_POLICY=block`,
         *     which does enforce merely-unverified rules. `PENDING` decides nothing and is a bookmark.
         *
         *     `reviewed_by` is required for a decision, for the same reason `approved_by` is on an approval:
         *     this changes what every future audit concludes about somebody's invoice. It is recorded, not
         *     authenticated.
         *
         *     The response carries the recomputed coverage, so a dashboard can update its progress bar from
         *     the same response rather than issuing a second request that could see a different world.
         */
        post: operations["review_rule_api_v1_rules__rule_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve
         * @description Run the deterministic pipeline and store the result as a DRAFT proposal.
         *
         *     The response is a proposal, never an invoice: `status` is `DRAFT` and stays there until a
         *     named person approves it via `POST /api/v1/proposals/{id}/approve`. `receipt_hash` identifies
         *     the catalog, rule tables, logic programs, solver versions, policy and input that produced it.
         */
        post: operations["solve_api_v1_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vocabulary
         * @description Exactly the clinical vocabulary the bridge can map, for a UI to offer as pickers.
         *
         *     Generated from `data/mappings/entity_to_ziffer.csv`, so it cannot drift from what the engine
         *     actually understands. This is what lets a form stop asking users to type identifiers like
         *     `vollstaendige_untersuchung_organsystem` — a typo there produces an `unmapped_entity` warning
         *     and the service is silently not charged.
         */
        get: operations["vocabulary_api_v1_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalogDecision */
        AnalogDecision: {
            /** Act Id */
            act_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Legal Basis
             * @default § 6 Abs. 2 GOÄ
             */
            legal_basis: string;
            /**
             * Quote
             * @default
             */
            quote: string;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Similarity */
            similarity: string;
            /** Ziffer */
            ziffer: string;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /**
             * Approved By
             * @description Who is accepting responsibility.
             */
            approved_by: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * AuditEventRecord
         * @description One row of the append-only log, as it is written in the database.
         */
        AuditEventRecord: {
            /** Actor */
            actor: string;
            /** Event Type */
            event_type: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /** AuditTrail */
        AuditTrail: {
            /**
             * Base Factor Policy
             * @default schwellenwert
             */
            base_factor_policy: string;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /**
             * Catalog Source
             * @default
             */
            catalog_source: string;
            /**
             * Catalog Version
             * @default
             */
            catalog_version: string;
            /**
             * Extraction Confidence Avg
             * @default 1.0
             */
            extraction_confidence_avg: string;
            /** Extraction Mode */
            extraction_mode: string;
            /**
             * Extraction Model
             * @default manual
             */
            extraction_model: string;
            /**
             * Llm Saw Goae Catalog
             * @default false
             */
            llm_saw_goae_catalog: boolean;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /**
             * Optimizer
             * @default clingo
             */
            optimizer: string;
            /**
             * Optimizer Version
             * @default
             */
            optimizer_version: string;
            /** Per Code */
            per_code?: components["schemas"]["AuditTrailEntry"][];
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /** Rule Summary */
            rule_summary?: {
                [key: string]: unknown;
            };
            /**
             * Rules Engine
             * @default souffle
             */
            rules_engine: string;
            /**
             * Rules Engine Version
             * @default
             */
            rules_engine_version: string;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Solver Status
             * @default
             */
            solver_status: string;
            /** Stage Timings Ms */
            stage_timings_ms?: {
                [key: string]: number;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Unverified Rule Policy
             * @default warn
             */
            unverified_rule_policy: string;
        };
        /** AuditTrailEntry */
        AuditTrailEntry: {
            /** Steps */
            steps?: components["schemas"]["ProofStep"][];
            /** Ziffer */
            ziffer: string;
        };
        /**
         * BatchAggregateSummary
         * @description The honest buckets, rolled up across every file that could be audited.
         *
         *     Every euro figure here is a sum of the identically-named field on the per-file
         *     `PadnextAuditReport`s, over files in status `COMPLETED`. Failed files are excluded from the
         *     money entirely — a file we could not read is not evidence of anything — and counted separately
         *     so the reader can see what the roll-up is missing.
         */
        BatchAggregateSummary: {
            /**
             * Claimed Total Eur
             * @default 0.00
             */
            claimed_total_eur: string;
            /**
             * Completed File Count
             * @default 0
             */
            completed_file_count: number;
            /**
             * Confirmed Fine Eur
             * @default 0.00
             */
            confirmed_fine_eur: string;
            /**
             * Confirmed Fine Positions
             * @default 0
             */
            confirmed_fine_positions: number;
            /**
             * Confirmed Wrong Eur
             * @default 0.00
             */
            confirmed_wrong_eur: string;
            /**
             * Confirmed Wrong Positions
             * @default 0
             */
            confirmed_wrong_positions: number;
            /**
             * Coverage Ratio
             * @default 0
             */
            coverage_ratio: number;
            /**
             * Failed File Count
             * @default 0
             */
            failed_file_count: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /**
             * Position Count
             * @default 0
             */
            position_count: number;
            /**
             * Unconfirmed Eur
             * @default 0.00
             */
            unconfirmed_eur: string;
            /**
             * Unconfirmed Positions
             * @default 0
             */
            unconfirmed_positions: number;
        };
        /**
         * BatchAuditAccepted
         * @description The `202` body: the handle to poll, and nothing that is not known yet.
         *
         *     Deliberately not a `BatchAuditJob` with empty fields. A response that carried a zeroed
         *     `aggregate_summary` would invite a client to render €0.00 across the dashboard for the second
         *     before its first poll returns.
         */
        BatchAuditAccepted: {
            /** Batch Id */
            batch_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** @default PENDING */
            status: components["schemas"]["BatchJobStatus"];
        };
        /**
         * BatchAuditJob
         * @description A batch, its progress, and — once it is done — the roll-up and every file's report.
         */
        BatchAuditJob: {
            aggregate_summary?: components["schemas"]["BatchAggregateSummary"] | null;
            /** Batch Id */
            batch_id: string;
            /** Completed At */
            completed_at?: string | null;
            /**
             * Completed File Count
             * @default 0
             */
            completed_file_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error Message */
            error_message?: string | null;
            /**
             * Failed File Count
             * @default 0
             */
            failed_file_count: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Files */
            files?: components["schemas"]["BatchFileResult"][];
            /**
             * Processed File Count
             * @default 0
             */
            processed_file_count: number;
            status: components["schemas"]["BatchJobStatus"];
        };
        /**
         * BatchFileResult
         * @description One uploaded file and what became of it.
         */
        BatchFileResult: {
            /** Error Message */
            error_message?: string | null;
            /** Filename */
            filename: string;
            report?: components["schemas"]["PadnextAuditReport"] | null;
            status: components["schemas"]["BatchFileStatus"];
        };
        /**
         * BatchFileStatus
         * @description Where one file in a batch is.
         *
         *     No `PROCESSING`: files are audited one after another and the transition out of `PENDING` is a
         *     single write at the end of the file's audit. A per-file in-progress state would be a second
         *     write per file bought for nothing — the job's own `PROCESSING` already says work is happening,
         *     and the count of files still `PENDING` already says how much is left.
         * @enum {string}
         */
        BatchFileStatus: "PENDING" | "COMPLETED" | "FAILED";
        /**
         * BatchJobStatus
         * @description Where a batch is in its life.
         *
         *     `FAILED` is deliberately narrow: it means the *batch itself* broke — the background task raised
         *     before it could finish, or the store refused a write — and there is no roll-up to show. A run in
         *     which every file failed to parse is `COMPLETED`, because the run did complete and its output is
         *     a hundred per-file error messages a user needs to read. Marking that `FAILED` would hide them
         *     behind a status that says "nothing to see".
         * @enum {string}
         */
        BatchJobStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /**
         * BilingualOption
         * @description An option whose label is interface text, so it exists in both languages.
         */
        BilingualOption: {
            /** Label De */
            label_de: string;
            /** Label En */
            label_en: string;
            /** Value */
            value: string;
        };
        /** BlockedCode */
        BlockedCode: {
            /** Blocked By */
            blocked_by?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Official Text
             * @default
             */
            official_text: string;
            /** Proof */
            proof?: components["schemas"]["ProofStep"][];
            /**
             * Reason
             * @enum {string}
             */
            reason: "exclusion" | "mutual_exclusion" | "zielleistung" | "less_specific" | "unknown_ziffer" | "inactive_ziffer" | "conflict_lost";
            /**
             * Reconciled With Final Invoice
             * @default true
             */
            reconciled_with_final_invoice: boolean;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer */
            ziffer: string;
        };
        /** Body_padnext_batch_api_v1_padnext_batch_post */
        Body_padnext_batch_api_v1_padnext_batch_post: {
            /**
             * Files
             * @description The PADnext deliveries to audit — .padx containers or *_padx.xml payloads. Synthetic data only.
             */
            files: string[];
        };
        /**
         * CatalogResponse
         * @description Catalog provenance and coverage — deliberately not the full 2000-entry dump.
         */
        CatalogResponse: {
            /**
             * Active Ziffern
             * @default 0
             */
            active_ziffern: number;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /** Catalog Version */
            catalog_version: string;
            /** Coverage Detail */
            coverage_detail?: {
                [key: string]: unknown;
            };
            /** Imported Rules */
            imported_rules?: {
                [key: string]: unknown;
            };
            /**
             * Overrides Applied
             * @default 0
             */
            overrides_applied: number;
            /** Provenance Breakdown */
            provenance_breakdown?: {
                [key: string]: number;
            };
            /**
             * Punktwert Cent
             * @default
             */
            punktwert_cent: string;
            /** Rounding */
            rounding?: {
                [key: string]: unknown;
            };
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            source?: components["schemas"]["CatalogSource"];
            /**
             * Text Quality Flagged
             * @default 0
             */
            text_quality_flagged: number;
            /** Warnings */
            warnings?: string[];
            /**
             * Ziffern
             * @default 0
             */
            ziffern: number;
        } & {
            [key: string]: unknown;
        };
        /** CatalogSource */
        CatalogSource: {
            /**
             * Legal Status
             * @default
             */
            legal_status: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Publisher
             * @default
             */
            publisher: string;
            /**
             * Retrieved At
             * @default
             */
            retrieved_at: string;
            /**
             * Sha256 Raw
             * @default
             */
            sha256_raw: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /**
         * ClinicalExtraction
         * @description Manual clinical entities. The pipeline's only input.
         */
        "ClinicalExtraction-Input": {
            consultation?: components["schemas"]["Consultation-Input"] | null;
            /** Diagnoses */
            diagnoses?: components["schemas"]["Diagnosis-Input"][];
            /** Examinations */
            examinations?: components["schemas"]["Examination-Input"][];
            /** Justification Factors */
            justification_factors?: components["schemas"]["JustificationFactor-Input"][];
            /** Lab Tests */
            lab_tests?: components["schemas"]["LabTest-Input"][];
            /**
             * Notes
             * @default
             */
            notes: string;
            patient?: components["schemas"]["Patient"];
            /** Procedures */
            procedures?: components["schemas"]["Procedure-Input"][];
        };
        /**
         * ClinicalExtraction
         * @description Manual clinical entities. The pipeline's only input.
         */
        "ClinicalExtraction-Output": {
            consultation?: components["schemas"]["Consultation-Output"] | null;
            /** Diagnoses */
            diagnoses?: components["schemas"]["Diagnosis-Output"][];
            /** Examinations */
            examinations?: components["schemas"]["Examination-Output"][];
            /** Justification Factors */
            justification_factors?: components["schemas"]["JustificationFactor-Output"][];
            /** Lab Tests */
            lab_tests?: components["schemas"]["LabTest-Output"][];
            /**
             * Notes
             * @default
             */
            notes: string;
            patient?: components["schemas"]["Patient"];
            /** Procedures */
            procedures?: components["schemas"]["Procedure-Output"][];
        };
        /** Coding */
        Coding: {
            /** Analog Codes */
            analog_codes?: components["schemas"]["AnalogDecision"][];
            /** Blocked Codes */
            blocked_codes?: components["schemas"]["BlockedCode"][];
            /** Conflicts Arbitrated */
            conflicts_arbitrated?: components["schemas"]["Conflict"][];
            /** Missing Documentation */
            missing_documentation?: components["schemas"]["MissingDocumentation"][];
            /** Proposed Codes */
            proposed_codes?: components["schemas"]["InvoiceLine"][];
            total?: components["schemas"]["Totals"];
            /** Warnings */
            warnings?: components["schemas"]["Warning_"][];
        };
        /**
         * CodingResponse
         * @description The invoice draft itself. Wrapped in a `Proposal` by the API.
         */
        CodingResponse: {
            audit_trail: components["schemas"]["AuditTrail"];
            coding: components["schemas"]["Coding"];
            extraction: components["schemas"]["ClinicalExtraction-Output"];
        };
        /**
         * ComplexityRef
         * @description A complexity an entity type actually has a mapping row for.
         *
         *     Carries no label on purpose: the display text for `einfach` / `mittel` / `komplex` is the same
         *     everywhere and lives once in the top-level `complexities` list. Repeating it per entity type
         *     would be three ways for the same word to disagree with itself.
         */
        ComplexityRef: {
            /** Value */
            value: string;
            /** Ziffern */
            ziffern?: string[];
        };
        /** Conflict */
        Conflict: {
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer A */
            ziffer_a: string;
            /** Ziffer B */
            ziffer_b: string;
        };
        /** Consultation */
        "Consultation-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /** Consultation */
        "Consultation-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /**
         * DecisionRecord
         * @description Who decided what, and when. The half of the document a dispute actually turns on.
         */
        DecisionRecord: {
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at: string;
            /** Exported By */
            exported_by: string;
            /** Rejected At */
            rejected_at?: string | null;
            /** Rejected By */
            rejected_by?: string | null;
            /** Rejected Reason */
            rejected_reason?: string | null;
        };
        /** Diagnosis */
        "Diagnosis-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Text */
            text: string;
        };
        /** Diagnosis */
        "Diagnosis-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * EngineIdentity
         * @description Everything that decides what the engine would answer, named and pinned.
         *
         *     Flattened out of the proposal rather than referenced, because an export is read on its own: a
         *     field that said "see the proposal" would be useless in a document whose whole purpose is to be
         *     separable from this database.
         */
        EngineIdentity: {
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /**
             * Catalog Version
             * @default
             */
            catalog_version: string;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /**
             * Rules Engine Version
             * @default
             */
            rules_engine_version: string;
            /**
             * Rules Hash
             * @default
             */
            rules_hash: string;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Solver Version
             * @default
             */
            solver_version: string;
        };
        /**
         * EntityTypeOption
         * @description One thing a user can record, with exactly the choices that map to something.
         */
        EntityTypeOption: {
            /**
             * Analog Only
             * @default false
             */
            analog_only: boolean;
            /** Complexities */
            complexities?: components["schemas"]["ComplexityRef"][];
            /**
             * Complexity Qualified
             * @default false
             */
            complexity_qualified: boolean;
            /** Entity Type */
            entity_type: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "consultation" | "examination" | "lab_test" | "procedure";
            /** Label De */
            label_de: string;
            /** Label En */
            label_en: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Organs */
            organs?: components["schemas"]["LabelledOption"][];
            /**
             * Requires Organ
             * @default false
             */
            requires_organ: boolean;
            /**
             * Requires Subtype
             * @default false
             */
            requires_subtype: boolean;
            /** Subtypes */
            subtypes?: components["schemas"]["LabelledOption"][];
            /** Ziffern */
            ziffern?: string[];
        };
        /** Examination */
        "Examination-Input": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ System */
            organ_system?: string | null;
            /** Organs */
            organs?: string[];
            /** Type */
            type: string;
        };
        /** Examination */
        "Examination-Output": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ System */
            organ_system?: string | null;
            /** Organs */
            organs?: string[];
            /** Type */
            type: string;
        };
        /**
         * ExportRequest
         * @description Who is taking the export.
         *
         *     Required for the same reason `approved_by` is required on an approval: an export is a thing a
         *     person did, and an unattributed one is indistinguishable from one nobody can account for. It is
         *     recorded, not verified — see the module docstring.
         */
        ExportRequest: {
            /**
             * Exported By
             * @description Who is taking this export. Recorded in the audit log; not authenticated.
             */
            exported_by: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Env */
            app_env: string;
            /**
             * Cache Enabled
             * @default true
             */
            cache_enabled: boolean;
            /**
             * Cache Entries
             * @default 0
             */
            cache_entries: number;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Catalog Ziffern
             * @default 0
             */
            catalog_ziffern: number;
            /**
             * Clingo Version
             * @default
             */
            clingo_version: string;
            /** Extraction Mode */
            extraction_mode: string;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /** Rule Coverage */
            rule_coverage: string;
            /**
             * Rules Enforced
             * @default 0
             */
            rules_enforced: number;
            /**
             * Solver Timeout Seconds
             * @default 0
             */
            solver_timeout_seconds: number;
            /** Souffle Available */
            souffle_available: boolean;
            /**
             * Souffle Version
             * @default
             */
            souffle_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Unverified Rules Not Enforced
             * @default 0
             */
            unverified_rules_not_enforced: number;
        };
        /** InvoiceLine */
        InvoiceLine: {
            /**
             * Amount Cent Unrounded
             * @default 0
             */
            amount_cent_unrounded: string;
            /**
             * Amount Eur
             * @default 0
             */
            amount_eur: string;
            /**
             * Amount Eur Before Minderung
             * @default 0
             */
            amount_eur_before_minderung: string;
            /** Analog For */
            analog_for?: string | null;
            /**
             * Catalog Provenance
             * @default official
             */
            catalog_provenance: string;
            /** Category */
            category: string | null;
            /** Confidence */
            confidence: string;
            /** Factor */
            factor: string;
            /**
             * Factor Basis
             * @enum {string}
             */
            factor_basis: "einfachsatz" | "schwellenwert" | "ueber_schwellenwert" | "hoechstsatz" | "capped";
            /**
             * Factor Legal Basis
             * @default
             */
            factor_legal_basis: string;
            /**
             * Is Analog
             * @default false
             */
            is_analog: boolean;
            /** Justification */
            justification?: string | null;
            /**
             * Justification Present
             * @default false
             */
            justification_present: boolean;
            /**
             * Justification Required
             * @default false
             */
            justification_required: boolean;
            /**
             * Minderung Applied
             * @default false
             */
            minderung_applied: boolean;
            /** Official Text */
            official_text: string;
            /** Proof */
            proof?: components["schemas"]["ProofStep"][];
            /** Punkte */
            punkte: number;
            /**
             * Status
             * @default billable
             * @enum {string}
             */
            status: "billable" | "billable_analog";
            /**
             * Text Quality
             * @default ok
             */
            text_quality: string;
            /** Ziffer */
            ziffer: string;
        };
        /** JustificationFactor */
        "JustificationFactor-Input": {
            /**
             * Applies To
             * @description Entity ids or entity types this refers to. Empty = the whole encounter.
             */
            applies_to?: string[];
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @default leicht
             * @enum {string}
             */
            severity: "leicht" | "mittel" | "schwer";
        };
        /** JustificationFactor */
        "JustificationFactor-Output": {
            /**
             * Applies To
             * @description Entity ids or entity types this refers to. Empty = the whole encounter.
             */
            applies_to?: string[];
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @default leicht
             * @enum {string}
             */
            severity: "leicht" | "mittel" | "schwer";
        };
        /** LabTest */
        "LabTest-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /** LabTest */
        "LabTest-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /**
         * LabelledOption
         * @description An option with one display label: an organ, a subtype, a complexity qualifier.
         *
         *     Organ and subtype names are clinical vocabulary and are deliberately NOT translated — the same
         *     reason GOÄ service texts are not. `ziffern` is informational, so a picker can show which
         *     position a choice leads to; the engine still decides.
         */
        LabelledOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Ziffern */
            ziffern?: string[];
        };
        /**
         * MissingDocumentation
         * @description A higher Steigerungsfaktor that the law would permit but the record does not support.
         *
         *     Derived only from what the existing logic already emits — the § 5 band, the cap, the ladder's
         *     own output and whether a written reason is present. **Nothing here changes what is billed.**
         *     The solver's objective is untouched: this is the gap between what was documented and what
         *     would have to be documented, stated so a physician can decide whether to document it.
         *
         *     ``current_factor`` is what the solver actually chose and what the invoice charges.
         *     ``possible_factor`` is the ceiling that a written justification (§ 12 Abs. 3 GOÄ) would open,
         *     never a proposal to charge it.
         */
        MissingDocumentation: {
            /** Current Factor */
            current_factor: string;
            /**
             * Legal Basis
             * @default § 12 Abs. 3 GOÄ
             */
            legal_basis: string;
            /** Missing */
            missing: string;
            /** Possible Factor */
            possible_factor: string;
            /** Ziffer */
            ziffer: string;
        };
        /** PadnextAuditReport */
        PadnextAuditReport: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /**
             * Arithmetic Delta Eur
             * @default 0.00
             */
            arithmetic_delta_eur: string;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /**
             * Catalog Version
             * @default
             */
            catalog_version: string;
            /**
             * Claimed Total Eur
             * @default 0.00
             */
            claimed_total_eur: string;
            /**
             * Comparable Claimed Eur
             * @default 0.00
             */
            comparable_claimed_eur: string;
            /**
             * Confirmed Fine Eur
             * @default 0.00
             */
            confirmed_fine_eur: string;
            /**
             * Confirmed Wrong Eur
             * @default 0.00
             */
            confirmed_wrong_eur: string;
            /**
             * Coverage Ratio
             * @default 0
             */
            coverage_ratio: number;
            /**
             * Defensible Total Eur
             * @default 0.00
             */
            defensible_total_eur: string;
            /** Echtdaten */
            echtdaten?: boolean | null;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /** Findings */
            findings?: components["schemas"]["PadnextFinding"][];
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /**
             * Nachrichtentyp
             * @default
             */
            nachrichtentyp: string;
            /** Positions */
            positions?: components["schemas"]["PadnextAuditedPosition"][];
            /**
             * Receipt Hash
             * @default
             */
            receipt_hash: string;
            /**
             * Recomputed Total Eur
             * @default 0.00
             */
            recomputed_total_eur: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Setting
             * @default ambulant
             * @enum {string}
             */
            setting: "ambulant" | "stationaer" | "belegarzt";
            /**
             * Setting Source
             * @default
             */
            setting_source: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /**
             * Unconfirmed Eur
             * @default 0.00
             */
            unconfirmed_eur: string;
            /**
             * Unpriceable Claimed Eur
             * @default 0.00
             */
            unpriceable_claimed_eur: string;
        };
        /**
         * PadnextAuditedPosition
         * @description A claimed position, with our verdict on it.
         */
        PadnextAuditedPosition: {
            /**
             * Accepted As Claimed
             * @default false
             */
            accepted_as_claimed: boolean;
            /** Advisory Rule Ids */
            advisory_rule_ids?: string[];
            /** Amount Delta Eur */
            amount_delta_eur?: string | null;
            /** Blocked By */
            blocked_by?: string | null;
            /**
             * Bucket
             * @default unconfirmed
             * @enum {string}
             */
            bucket: "confirmed_fine" | "confirmed_wrong" | "unconfirmed";
            /**
             * Bucket Reason
             * @default
             */
            bucket_reason: string;
            /** Claimed Amount Eur */
            claimed_amount_eur?: string | null;
            /** Claimed Faktor */
            claimed_faktor?: string | null;
            /** Factor Within Band */
            factor_within_band?: boolean | null;
            /** Go */
            go: string;
            /**
             * In Catalog
             * @default false
             */
            in_catalog: boolean;
            /**
             * Is Analog
             * @default false
             */
            is_analog: boolean;
            /**
             * Justification Present
             * @default false
             */
            justification_present: boolean;
            /**
             * Justification Required
             * @default false
             */
            justification_required: boolean;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Official Text
             * @default
             */
            official_text: string;
            /** Positionsnr */
            positionsnr: string;
            /** Proof */
            proof?: string[];
            /** Punkte */
            punkte?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Recomputed Amount Eur */
            recomputed_amount_eur?: string | null;
            /**
             * Verdict
             * @default chargeable
             * @enum {string}
             */
            verdict: "chargeable" | "blocked" | "out_of_scope" | "unknown_ziffer";
            /** Verified Rule Ids */
            verified_rule_ids?: string[];
            /** Ziffer */
            ziffer: string;
        };
        /**
         * PadnextFinding
         * @description Something the audit noticed. Every non-chargeable position produces at least one.
         */
        PadnextFinding: {
            /** Claimed */
            claimed?: string | null;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Message */
            message: string;
            /** Positionsnr */
            positionsnr?: string | null;
            /** Recomputed */
            recomputed?: string | null;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /**
             * Severity
             * @default warning
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Type */
            type: string;
            /** Ziffer */
            ziffer?: string | null;
        };
        /** Patient */
        Patient: {
            /** Age */
            age?: number | null;
            /**
             * Setting
             * @default ambulant
             * @enum {string}
             */
            setting: "ambulant" | "stationaer" | "belegarzt";
            /** Sex */
            sex?: ("m" | "w" | "d") | null;
        };
        /** Procedure */
        "Procedure-Input": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ */
            organ?: string | null;
            /** Type */
            type: string;
        };
        /** Procedure */
        "Procedure-Output": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ */
            organ?: string | null;
            /** Type */
            type: string;
        };
        /** ProofStep */
        ProofStep: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Rule */
            rule: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer */
            ziffer: string;
        };
        /**
         * Proposal
         * @description One solve, wrapped with everything a reviewer needs to accept or refuse it.
         */
        Proposal: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /**
             * Analog Candidate Count
             * @default 0
             */
            analog_candidate_count: number;
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Case Id */
            case_id?: string | null;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /** Missing Documentation */
            missing_documentation?: components["schemas"]["MissingDocumentation"][];
            /** Proposal Id */
            proposal_id: string;
            /** Receipt Hash */
            receipt_hash: string;
            /** Rejected Reason */
            rejected_reason?: string | null;
            rule_coverage?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Engine Version
             * @default
             */
            rules_engine_version: string;
            /**
             * Rules Hash
             * @default
             */
            rules_hash: string;
            /** Rules Version */
            rules_version: string;
            solver_result: components["schemas"]["CodingResponse"];
            /**
             * Solver Status
             * @default
             */
            solver_status: string;
            /**
             * Solver Timed Out
             * @default false
             */
            solver_timed_out: boolean;
            /** Solver Version */
            solver_version: string;
            /** @default DRAFT */
            status: components["schemas"]["ProposalStatus"];
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /**
             * Unverified Rule Count
             * @default 0
             */
            unverified_rule_count: number;
            /** Warnings */
            warnings?: components["schemas"]["Warning_"][];
        };
        /**
         * ProposalExport
         * @description The downloadable record of one approved proposal.
         *
         *     Served as `{proposal_id}.json` with a `Content-Disposition: attachment` header. The
         *     JSON is the contract; the filename is a convenience.
         */
        ProposalExport: {
            /** Audit Events */
            audit_events?: components["schemas"]["AuditEventRecord"][];
            /** Case Id */
            case_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            decision: components["schemas"]["DecisionRecord"];
            engine: components["schemas"]["EngineIdentity"];
            /**
             * Export Format Version
             * @default 1.0
             */
            export_format_version: string;
            /** Input Hash */
            input_hash: string;
            /** Missing Documentation */
            missing_documentation?: components["schemas"]["MissingDocumentation"][];
            /** Proposal Id */
            proposal_id: string;
            /** Receipt Hash */
            receipt_hash: string;
            rule_coverage?: components["schemas"]["RuleCoverage"] | null;
            solver_result: components["schemas"]["CodingResponse"];
            /** Status */
            status: string;
            /** Warnings */
            warnings?: components["schemas"]["Warning_"][];
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "DRAFT" | "APPROVED" | "REJECTED" | "EXPORTED";
        /** RejectionRequest */
        RejectionRequest: {
            /** Reason */
            reason: string;
            /** Rejected By */
            rejected_by: string;
        };
        /**
         * ReviewableRule
         * @description One rule as the review queue presents it — everything needed to decide, and nothing else.
         */
        ReviewableRule: {
            /**
             * Csv Verified
             * @default false
             */
            csv_verified: boolean;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            };
            /**
             * Kind
             * @enum {string}
             */
            kind: "exclusion" | "zielleistung" | "specificity" | "factor_cap";
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Quote
             * @default
             */
            quote: string;
            /** Review Notes */
            review_notes?: string | null;
            /** Review Status */
            review_status?: ("VERIFIED" | "REJECTED" | "PENDING") | null;
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Reviewed By */
            reviewed_by?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Source
             * @default
             */
            source: string;
            /**
             * Verified
             * @default false
             */
            verified: boolean;
            /** Ziffer Roles */
            ziffer_roles?: {
                [key: string]: string;
            };
            /** Ziffern */
            ziffern?: string[];
        };
        /**
         * RuleCoverage
         * @description How much of the rule set is actually being enforced, on every response that has one.
         *
         *     The API must never imply that unverified rules are enforced. ``enforced_rule_count`` is what
         *     can suppress a position; ``advisory_rule_count`` is what only warns. Under the default
         *     ``UNVERIFIED_RULE_POLICY=warn`` the advisory set is the automatically extracted majority, and
         *     a response carrying a non-zero advisory count also carries a warning saying so.
         */
        RuleCoverage: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /**
             * Analog Candidate Count
             * @default 0
             */
            analog_candidate_count: number;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /** Policy For Unverified Rules */
            policy_for_unverified_rules: string;
            /**
             * Rejected Rule Count
             * @default 0
             */
            rejected_rule_count: number;
            /**
             * Review Verified Rule Count
             * @default 0
             */
            review_verified_rule_count: number;
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /**
             * Total Constraint Rule Count
             * @default 0
             */
            total_constraint_rule_count: number;
            /**
             * Unverified Rule Count
             * @default 0
             */
            unverified_rule_count: number;
            /**
             * Verified Share
             * @default 0/0
             */
            verified_share: string;
        };
        /**
         * RuleReviewQueue
         * @description The rules still awaiting a decision, with enough context to show progress.
         */
        RuleReviewQueue: {
            /**
             * Pending Rule Count
             * @default 0
             */
            pending_rule_count: number;
            /**
             * Rejected Rule Count
             * @default 0
             */
            rejected_rule_count: number;
            /**
             * Review Verified Rule Count
             * @default 0
             */
            review_verified_rule_count: number;
            /** Rules */
            rules?: components["schemas"]["ReviewableRule"][];
            /**
             * Total Constraint Rules
             * @default 0
             */
            total_constraint_rules: number;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Verified Rule Count
             * @default 0
             */
            verified_rule_count: number;
        };
        /**
         * RuleReviewRequest
         * @description A reviewer's verdict on one rule.
         */
        RuleReviewRequest: {
            /**
             * Review Notes
             * @default
             */
            review_notes: string;
            /**
             * Reviewed By
             * @default
             */
            reviewed_by: string;
            /**
             * Status
             * @enum {string}
             */
            status: "VERIFIED" | "REJECTED" | "PENDING";
        };
        /**
         * RuleReviewResult
         * @description The rule after the review was applied, plus the coverage it moved.
         */
        RuleReviewResult: {
            coverage: components["schemas"]["RuleCoverage"];
            rule: components["schemas"]["ReviewableRule"];
        };
        /**
         * SolveRequest
         * @description ``POST /api/v1/solve`` — clinical entities in, an auditable draft out.
         *
         *     Accepts either the envelope ``{"extraction": {...}, "setting": ...}`` or a bare extraction
         *     posted directly, because ``curl -d @logic/tests/cases/case_001_knee/input.json`` is the
         *     obvious thing to reach for and the case files are bare extractions.
         */
        SolveRequest: {
            /**
             * Case Id
             * @description Caller's identifier for this encounter, echoed onto the proposal.
             */
            case_id?: string | null;
            extraction: components["schemas"]["ClinicalExtraction-Input"];
            /**
             * Setting
             * @description Overrides patient.setting; drives § 6a Minderung.
             */
            setting?: ("ambulant" | "stationaer" | "belegarzt") | null;
        };
        /** Totals */
        Totals: {
            /**
             * Amount Cent Unrounded
             * @default 0
             */
            amount_cent_unrounded: string;
            /**
             * Amount Eur
             * @default 0
             */
            amount_eur: string;
            /**
             * Amount Eur Before Minderung
             * @default 0
             */
            amount_eur_before_minderung: string;
            /**
             * Minderung Applied
             * @default false
             */
            minderung_applied: boolean;
            /**
             * Minderung Rate
             * @default 0
             */
            minderung_rate: string;
            /**
             * Punkte
             * @default 0
             */
            punkte: number;
            /**
             * Punktwert Cent
             * @default 5.82873
             */
            punktwert_cent: string;
            /**
             * Rounding Legal Basis
             * @default
             */
            rounding_legal_basis: string;
            /**
             * Rounding Policy
             * @default ROUND_HALF_UP
             */
            rounding_policy: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VocabularyResponse
         * @description What `GET /api/v1/vocabulary` returns.
         *
         *     Declared as a model rather than a bare dict for one concrete reason: an endpoint with no
         *     OpenAPI schema cannot have a TypeScript client generated for it, so the front end wrote one by
         *     hand and got the shape wrong in three ways — `entity_types` declared as a flat array when the
         *     API returns a mapping keyed by kind, options keyed on `value` rather than `entity_type`, and an
         *     invented `sexes` list. None of it failed a type check on either side.
         *
         *     `entity_types` is a mapping so a UI can group the pickers without re-deriving groups.
         */
        VocabularyResponse: {
            /** Catalog Version */
            catalog_version: string;
            /** Complexities */
            complexities: components["schemas"]["BilingualOption"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Entity Types */
            entity_types: {
                [key: string]: components["schemas"]["EntityTypeOption"][];
            };
            /** Settings */
            settings: components["schemas"]["BilingualOption"][];
            /** Severities */
            severities: components["schemas"]["BilingualOption"][];
        };
        /**
         * Warning_
         * @description A non-fatal finding. Named with a trailing underscore to avoid the builtin.
         */
        Warning_: {
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Message */
            message: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /**
             * Severity
             * @default warning
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Type */
            type: string;
            /** Ziffer */
            ziffer?: string | null;
        };
        /**
         * ZifferResponse
         * @description One catalog position, with the rules that touch it.
         */
        ZifferResponse: {
            /** Annotations */
            annotations?: string[];
            /** Category */
            category?: string | null;
            /** Exclusions Enforced */
            exclusions_enforced?: {
                [key: string]: unknown;
            }[];
            /** Factor Band */
            factor_band?: {
                [key: string]: unknown;
            };
            /** Factor Cap */
            factor_cap?: {
                [key: string]: unknown;
            } | null;
            /**
             * Minderung Exempt
             * @default false
             */
            minderung_exempt: boolean;
            /** Official Text */
            official_text: string;
            /**
             * Provenance
             * @default official
             */
            provenance: string;
            /** Punkte */
            punkte: number;
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            /** Section */
            section?: string | null;
            /** Section Title */
            section_title?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Text Quality
             * @default ok
             */
            text_quality: string;
            /** Ziffer */
            ziffer: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    catalog_ziffer_api_v1_catalog_ziffer__ziffer__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ziffer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZifferResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    padnext_audit_api_v1_padnext_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PadnextAuditReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    padnext_batch_api_v1_padnext_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_padnext_batch_api_v1_padnext_batch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAuditAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    padnext_batch_status_api_v1_padnext_batch__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchAuditJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    padnext_batch_export_api_v1_padnext_batch__batch_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A ZIP archive named `{batch_id}_export.zip` holding `batch_summary.csv`, `batch_line_items.csv`, `batch_files.csv` and a `README.txt` that defines the three buckets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            /** @description The batch has not completed, so there is no roll-up to export. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_v1_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_v1_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_proposal_api_v1_proposals__proposal_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description The export document, as a downloadable attachment named `{proposal_id}.json`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalExport"];
                };
            };
            /** @description The proposal is not APPROVED, so there is nothing to export. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rule_coverage_api_v1_rules_coverage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleCoverage"];
                };
            };
        };
    };
    review_queue_api_v1_rules_review_queue_get: {
        parameters: {
            query?: {
                /** @description Show one rule type only. `zielleistung` first is the usual order of work: a wrong Zielleistung rule removes a position a practice was entitled to charge. */
                kind?: ("exclusion" | "zielleistung" | "specificity" | "factor_cap") | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReviewQueue"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_rule_api_v1_rules__rule_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleReviewResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_api_v1_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vocabulary_api_v1_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"];
                };
            };
        };
    };
}
