/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Catalog
         * @description Provenance and coverage — deliberately not the full 2000-entry dump.
         *
         *     The warnings are not decoration: rule coverage is `partial`, most exclusion rules were
         *     machine-extracted and are unverified, and no Zielleistung pairs are loaded at all. Publishing
         *     that is the difference between a defensible tool and one that overclaims.
         */
        get: operations["catalog_api_v1_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/ziffer/{ziffer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog Ziffer */
        get: operations["catalog_ziffer_api_v1_catalog_ziffer__ziffer__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/padnext/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Padnext Audit
         * @description Audit a PADnext delivery against the GOÄ rules.
         *
         *     The body is the file itself, not a JSON wrapper or a multipart upload: either a `.padx`
         *     container (a ZIP, sniffed by magic bytes) or a bare `*_padx.xml` payload. Taking raw bytes
         *     avoids a `python-multipart` dependency for what is one file per request.
         *
         *     A delivery flagged as production data is refused with 422 — see `app.padnext.audit` and
         *     `docs/compliance/PRIVATE_DATA_WARNING.md`.
         */
        post: operations["padnext_audit_api_v1_padnext_audit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_v1_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_v1_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve
         * @description Accept a draft. `approved_by` is required — an unattributed approval is not one.
         */
        post: operations["approve_api_v1_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Exported
         * @description Record that an approved proposal left the system. Only reachable from APPROVED.
         */
        post: operations["mark_exported_api_v1_proposals__proposal_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject
         * @description Refuse a draft, with a reason. Terminal: a rejected draft is not re-decided, it is re-run.
         */
        post: operations["reject_api_v1_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve
         * @description Run the deterministic pipeline and store the result as a DRAFT proposal.
         *
         *     The response is a proposal, never an invoice: `status` is `DRAFT` and stays there until a
         *     named person approves it via `POST /api/v1/proposals/{id}/approve`. `receipt_hash` identifies
         *     the catalog, rule tables, logic programs, solver versions, policy and input that produced it.
         */
        post: operations["solve_api_v1_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vocabulary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vocabulary
         * @description Exactly the clinical vocabulary the bridge can map, for a UI to offer as pickers.
         *
         *     Generated from `data/mappings/entity_to_ziffer.csv`, so it cannot drift from what the engine
         *     actually understands. This is what lets a form stop asking users to type identifiers like
         *     `vollstaendige_untersuchung_organsystem` — a typo there produces an `unmapped_entity` warning
         *     and the service is silently not charged.
         */
        get: operations["vocabulary_api_v1_vocabulary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalogDecision */
        AnalogDecision: {
            /** Act Id */
            act_id: string;
            /** Entity Type */
            entity_type: string;
            /**
             * Legal Basis
             * @default § 6 Abs. 2 GOÄ
             */
            legal_basis: string;
            /**
             * Quote
             * @default
             */
            quote: string;
            /**
             * Requires Human Review
             * @default true
             */
            requires_human_review: boolean;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Similarity */
            similarity: string;
            /** Ziffer */
            ziffer: string;
        };
        /** ApprovalRequest */
        ApprovalRequest: {
            /**
             * Approved By
             * @description Who is accepting responsibility.
             */
            approved_by: string;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** AuditTrail */
        AuditTrail: {
            /**
             * Base Factor Policy
             * @default schwellenwert
             */
            base_factor_policy: string;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /**
             * Catalog Source
             * @default
             */
            catalog_source: string;
            /**
             * Catalog Version
             * @default
             */
            catalog_version: string;
            /**
             * Extraction Confidence Avg
             * @default 1.0
             */
            extraction_confidence_avg: string;
            /** Extraction Mode */
            extraction_mode: string;
            /**
             * Extraction Model
             * @default manual
             */
            extraction_model: string;
            /**
             * Llm Saw Goae Catalog
             * @default false
             */
            llm_saw_goae_catalog: boolean;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /**
             * Optimizer
             * @default clingo
             */
            optimizer: string;
            /**
             * Optimizer Version
             * @default
             */
            optimizer_version: string;
            /** Per Code */
            per_code?: components["schemas"]["AuditTrailEntry"][];
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /** Rule Summary */
            rule_summary?: {
                [key: string]: unknown;
            };
            /**
             * Rules Engine
             * @default souffle
             */
            rules_engine: string;
            /**
             * Rules Engine Version
             * @default
             */
            rules_engine_version: string;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Solver Status
             * @default
             */
            solver_status: string;
            /** Stage Timings Ms */
            stage_timings_ms?: {
                [key: string]: number;
            };
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /**
             * Unverified Rule Policy
             * @default warn
             */
            unverified_rule_policy: string;
        };
        /** AuditTrailEntry */
        AuditTrailEntry: {
            /** Steps */
            steps?: components["schemas"]["ProofStep"][];
            /** Ziffer */
            ziffer: string;
        };
        /**
         * BilingualOption
         * @description An option whose label is interface text, so it exists in both languages.
         */
        BilingualOption: {
            /** Label De */
            label_de: string;
            /** Label En */
            label_en: string;
            /** Value */
            value: string;
        };
        /** BlockedCode */
        BlockedCode: {
            /** Blocked By */
            blocked_by?: string | null;
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Official Text
             * @default
             */
            official_text: string;
            /**
             * Reason
             * @enum {string}
             */
            reason: "exclusion" | "mutual_exclusion" | "zielleistung" | "less_specific" | "unknown_ziffer" | "inactive_ziffer" | "conflict_lost";
            /**
             * Reconciled With Final Invoice
             * @default true
             */
            reconciled_with_final_invoice: boolean;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer */
            ziffer: string;
        };
        /**
         * CatalogResponse
         * @description Catalog provenance and coverage — deliberately not the full 2000-entry dump.
         */
        CatalogResponse: {
            /**
             * Active Ziffern
             * @default 0
             */
            active_ziffern: number;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /** Catalog Version */
            catalog_version: string;
            /** Coverage Detail */
            coverage_detail?: {
                [key: string]: unknown;
            };
            /** Imported Rules */
            imported_rules?: {
                [key: string]: unknown;
            };
            /**
             * Overrides Applied
             * @default 0
             */
            overrides_applied: number;
            /** Provenance Breakdown */
            provenance_breakdown?: {
                [key: string]: number;
            };
            /**
             * Punktwert Cent
             * @default
             */
            punktwert_cent: string;
            /** Rounding */
            rounding?: {
                [key: string]: unknown;
            };
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            source?: components["schemas"]["CatalogSource"];
            /**
             * Text Quality Flagged
             * @default 0
             */
            text_quality_flagged: number;
            /** Warnings */
            warnings?: string[];
            /**
             * Ziffern
             * @default 0
             */
            ziffern: number;
        } & {
            [key: string]: unknown;
        };
        /** CatalogSource */
        CatalogSource: {
            /**
             * Legal Status
             * @default
             */
            legal_status: string;
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Publisher
             * @default
             */
            publisher: string;
            /**
             * Retrieved At
             * @default
             */
            retrieved_at: string;
            /**
             * Sha256 Raw
             * @default
             */
            sha256_raw: string;
            /**
             * Url
             * @default
             */
            url: string;
        };
        /**
         * ClinicalExtraction
         * @description Manual clinical entities. The pipeline's only input.
         */
        "ClinicalExtraction-Input": {
            consultation?: components["schemas"]["Consultation-Input"] | null;
            /** Diagnoses */
            diagnoses?: components["schemas"]["Diagnosis-Input"][];
            /** Examinations */
            examinations?: components["schemas"]["Examination-Input"][];
            /** Justification Factors */
            justification_factors?: components["schemas"]["JustificationFactor-Input"][];
            /** Lab Tests */
            lab_tests?: components["schemas"]["LabTest-Input"][];
            /**
             * Notes
             * @default
             */
            notes: string;
            patient?: components["schemas"]["Patient"];
            /** Procedures */
            procedures?: components["schemas"]["Procedure-Input"][];
        };
        /**
         * ClinicalExtraction
         * @description Manual clinical entities. The pipeline's only input.
         */
        "ClinicalExtraction-Output": {
            consultation?: components["schemas"]["Consultation-Output"] | null;
            /** Diagnoses */
            diagnoses?: components["schemas"]["Diagnosis-Output"][];
            /** Examinations */
            examinations?: components["schemas"]["Examination-Output"][];
            /** Justification Factors */
            justification_factors?: components["schemas"]["JustificationFactor-Output"][];
            /** Lab Tests */
            lab_tests?: components["schemas"]["LabTest-Output"][];
            /**
             * Notes
             * @default
             */
            notes: string;
            patient?: components["schemas"]["Patient"];
            /** Procedures */
            procedures?: components["schemas"]["Procedure-Output"][];
        };
        /** Coding */
        Coding: {
            /** Analog Codes */
            analog_codes?: components["schemas"]["AnalogDecision"][];
            /** Blocked Codes */
            blocked_codes?: components["schemas"]["BlockedCode"][];
            /** Conflicts Arbitrated */
            conflicts_arbitrated?: components["schemas"]["Conflict"][];
            /** Missing Documentation */
            missing_documentation?: components["schemas"]["MissingDocumentation"][];
            /** Proposed Codes */
            proposed_codes?: components["schemas"]["InvoiceLine"][];
            total?: components["schemas"]["Totals"];
            /** Warnings */
            warnings?: components["schemas"]["Warning_"][];
        };
        /**
         * CodingResponse
         * @description The invoice draft itself. Wrapped in a `Proposal` by the API.
         */
        CodingResponse: {
            audit_trail: components["schemas"]["AuditTrail"];
            coding: components["schemas"]["Coding"];
            extraction: components["schemas"]["ClinicalExtraction-Output"];
        };
        /**
         * ComplexityRef
         * @description A complexity an entity type actually has a mapping row for.
         *
         *     Carries no label on purpose: the display text for `einfach` / `mittel` / `komplex` is the same
         *     everywhere and lives once in the top-level `complexities` list. Repeating it per entity type
         *     would be three ways for the same word to disagree with itself.
         */
        ComplexityRef: {
            /** Value */
            value: string;
            /** Ziffern */
            ziffern?: string[];
        };
        /** Conflict */
        Conflict: {
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer A */
            ziffer_a: string;
            /** Ziffer B */
            ziffer_b: string;
        };
        /** Consultation */
        "Consultation-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /** Consultation */
        "Consultation-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /** Diagnosis */
        "Diagnosis-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Text */
            text: string;
        };
        /** Diagnosis */
        "Diagnosis-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Text */
            text: string;
        };
        /**
         * EntityTypeOption
         * @description One thing a user can record, with exactly the choices that map to something.
         */
        EntityTypeOption: {
            /**
             * Analog Only
             * @default false
             */
            analog_only: boolean;
            /** Complexities */
            complexities?: components["schemas"]["ComplexityRef"][];
            /**
             * Complexity Qualified
             * @default false
             */
            complexity_qualified: boolean;
            /** Entity Type */
            entity_type: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "consultation" | "examination" | "lab_test" | "procedure";
            /** Label De */
            label_de: string;
            /** Label En */
            label_en: string;
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Organs */
            organs?: components["schemas"]["LabelledOption"][];
            /**
             * Requires Organ
             * @default false
             */
            requires_organ: boolean;
            /**
             * Requires Subtype
             * @default false
             */
            requires_subtype: boolean;
            /** Subtypes */
            subtypes?: components["schemas"]["LabelledOption"][];
            /** Ziffern */
            ziffern?: string[];
        };
        /** Examination */
        "Examination-Input": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ System */
            organ_system?: string | null;
            /** Organs */
            organs?: string[];
            /** Type */
            type: string;
        };
        /** Examination */
        "Examination-Output": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ System */
            organ_system?: string | null;
            /** Organs */
            organs?: string[];
            /** Type */
            type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App Env */
            app_env: string;
            /**
             * Cache Enabled
             * @default true
             */
            cache_enabled: boolean;
            /**
             * Cache Entries
             * @default 0
             */
            cache_entries: number;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Catalog Ziffern
             * @default 0
             */
            catalog_ziffern: number;
            /**
             * Clingo Version
             * @default
             */
            clingo_version: string;
            /** Extraction Mode */
            extraction_mode: string;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /** Rule Coverage */
            rule_coverage: string;
            /**
             * Rules Enforced
             * @default 0
             */
            rules_enforced: number;
            /**
             * Solver Timeout Seconds
             * @default 0
             */
            solver_timeout_seconds: number;
            /** Souffle Available */
            souffle_available: boolean;
            /**
             * Souffle Version
             * @default
             */
            souffle_version: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Unverified Rules Not Enforced
             * @default 0
             */
            unverified_rules_not_enforced: number;
        };
        /** InvoiceLine */
        InvoiceLine: {
            /**
             * Amount Cent Unrounded
             * @default 0
             */
            amount_cent_unrounded: string;
            /**
             * Amount Eur
             * @default 0
             */
            amount_eur: string;
            /**
             * Amount Eur Before Minderung
             * @default 0
             */
            amount_eur_before_minderung: string;
            /** Analog For */
            analog_for?: string | null;
            /**
             * Catalog Provenance
             * @default official
             */
            catalog_provenance: string;
            /** Category */
            category: string | null;
            /** Confidence */
            confidence: string;
            /** Factor */
            factor: string;
            /** Factor Basis */
            factor_basis: string;
            /**
             * Factor Legal Basis
             * @default
             */
            factor_legal_basis: string;
            /**
             * Is Analog
             * @default false
             */
            is_analog: boolean;
            /** Justification */
            justification?: string | null;
            /**
             * Justification Present
             * @default false
             */
            justification_present: boolean;
            /**
             * Justification Required
             * @default false
             */
            justification_required: boolean;
            /**
             * Minderung Applied
             * @default false
             */
            minderung_applied: boolean;
            /** Official Text */
            official_text: string;
            /** Proof */
            proof?: components["schemas"]["ProofStep"][];
            /** Punkte */
            punkte: number;
            /**
             * Status
             * @default billable
             * @enum {string}
             */
            status: "billable" | "billable_analog";
            /**
             * Text Quality
             * @default ok
             */
            text_quality: string;
            /** Ziffer */
            ziffer: string;
        };
        /** JustificationFactor */
        "JustificationFactor-Input": {
            /**
             * Applies To
             * @description Entity ids or entity types this refers to. Empty = the whole encounter.
             */
            applies_to?: string[];
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @default leicht
             * @enum {string}
             */
            severity: "leicht" | "mittel" | "schwer";
        };
        /** JustificationFactor */
        "JustificationFactor-Output": {
            /**
             * Applies To
             * @description Entity ids or entity types this refers to. Empty = the whole encounter.
             */
            applies_to?: string[];
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @default leicht
             * @enum {string}
             */
            severity: "leicht" | "mittel" | "schwer";
        };
        /** LabTest */
        "LabTest-Input": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /** LabTest */
        "LabTest-Output": {
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Type */
            type: string;
        };
        /**
         * LabelledOption
         * @description An option with one display label: an organ, a subtype, a complexity qualifier.
         *
         *     Organ and subtype names are clinical vocabulary and are deliberately NOT translated — the same
         *     reason GOÄ service texts are not. `ziffern` is informational, so a picker can show which
         *     position a choice leads to; the engine still decides.
         */
        LabelledOption: {
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Ziffern */
            ziffern?: string[];
        };
        /**
         * MissingDocumentation
         * @description A higher Steigerungsfaktor that the law would permit but the record does not support.
         *
         *     Derived only from what the existing logic already emits — the § 5 band, the cap, the ladder's
         *     own output and whether a written reason is present. **Nothing here changes what is billed.**
         *     The solver's objective is untouched: this is the gap between what was documented and what
         *     would have to be documented, stated so a physician can decide whether to document it.
         *
         *     ``current_factor`` is what the solver actually chose and what the invoice charges.
         *     ``possible_factor`` is the ceiling that a written justification (§ 12 Abs. 3 GOÄ) would open,
         *     never a proposal to charge it.
         */
        MissingDocumentation: {
            /** Current Factor */
            current_factor: string;
            /**
             * Legal Basis
             * @default § 12 Abs. 3 GOÄ
             */
            legal_basis: string;
            /** Missing */
            missing: string;
            /** Possible Factor */
            possible_factor: string;
            /** Ziffer */
            ziffer: string;
        };
        /** PadnextAuditReport */
        PadnextAuditReport: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /**
             * Arithmetic Delta Eur
             * @default 0.00
             */
            arithmetic_delta_eur: string;
            /**
             * At Risk Eur
             * @default 0.00
             */
            at_risk_eur: string;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /**
             * Catalog Version
             * @default
             */
            catalog_version: string;
            /**
             * Claimed Total Eur
             * @default 0.00
             */
            claimed_total_eur: string;
            /**
             * Comparable Claimed Eur
             * @default 0.00
             */
            comparable_claimed_eur: string;
            /**
             * Defensible Total Eur
             * @default 0.00
             */
            defensible_total_eur: string;
            /** Echtdaten */
            echtdaten?: boolean | null;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /** Findings */
            findings?: components["schemas"]["PadnextFinding"][];
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /**
             * Nachrichtentyp
             * @default
             */
            nachrichtentyp: string;
            /** Positions */
            positions?: components["schemas"]["PadnextAuditedPosition"][];
            /**
             * Receipt Hash
             * @default
             */
            receipt_hash: string;
            /**
             * Recomputed Total Eur
             * @default 0.00
             */
            recomputed_total_eur: string;
            rule_coverage_detail?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Setting
             * @default ambulant
             * @enum {string}
             */
            setting: "ambulant" | "stationaer" | "belegarzt";
            /**
             * Setting Source
             * @default
             */
            setting_source: string;
            /**
             * Source Name
             * @default
             */
            source_name: string;
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /**
             * Unpriceable Claimed Eur
             * @default 0.00
             */
            unpriceable_claimed_eur: string;
        };
        /**
         * PadnextAuditedPosition
         * @description A claimed position, with our verdict on it.
         */
        PadnextAuditedPosition: {
            /**
             * Accepted As Claimed
             * @default false
             */
            accepted_as_claimed: boolean;
            /** Amount Delta Eur */
            amount_delta_eur?: string | null;
            /** Blocked By */
            blocked_by?: string | null;
            /** Claimed Amount Eur */
            claimed_amount_eur?: string | null;
            /** Claimed Faktor */
            claimed_faktor?: string | null;
            /** Factor Within Band */
            factor_within_band?: boolean | null;
            /** Go */
            go: string;
            /**
             * In Catalog
             * @default false
             */
            in_catalog: boolean;
            /**
             * Is Analog
             * @default false
             */
            is_analog: boolean;
            /**
             * Justification Present
             * @default false
             */
            justification_present: boolean;
            /**
             * Justification Required
             * @default false
             */
            justification_required: boolean;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /**
             * Official Text
             * @default
             */
            official_text: string;
            /** Positionsnr */
            positionsnr: string;
            /** Proof */
            proof?: string[];
            /** Punkte */
            punkte?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Recomputed Amount Eur */
            recomputed_amount_eur?: string | null;
            /**
             * Verdict
             * @default chargeable
             * @enum {string}
             */
            verdict: "chargeable" | "blocked" | "out_of_scope" | "unknown_ziffer";
            /** Ziffer */
            ziffer: string;
        };
        /**
         * PadnextFinding
         * @description Something the audit noticed. Every non-chargeable position produces at least one.
         */
        PadnextFinding: {
            /** Claimed */
            claimed?: string | null;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Message */
            message: string;
            /** Positionsnr */
            positionsnr?: string | null;
            /** Recomputed */
            recomputed?: string | null;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /**
             * Severity
             * @default warning
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Type */
            type: string;
            /** Ziffer */
            ziffer?: string | null;
        };
        /** Patient */
        Patient: {
            /** Age */
            age?: number | null;
            /**
             * Setting
             * @default ambulant
             * @enum {string}
             */
            setting: "ambulant" | "stationaer" | "belegarzt";
            /** Sex */
            sex?: ("m" | "w" | "d") | null;
        };
        /** Procedure */
        "Procedure-Input": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: number | string;
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ */
            organ?: string | null;
            /** Type */
            type: string;
        };
        /** Procedure */
        "Procedure-Output": {
            /**
             * Complexity
             * @default mittel
             * @enum {string}
             */
            complexity: "einfach" | "mittel" | "komplex";
            /**
             * Confidence
             * @default 1.0
             */
            confidence: string;
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Id
             * @description Stable identifier, assigned if omitted.
             */
            id?: string | null;
            /** Organ */
            organ?: string | null;
            /** Type */
            type: string;
        };
        /** ProofStep */
        ProofStep: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Rule */
            rule: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /** Ziffer */
            ziffer: string;
        };
        /**
         * Proposal
         * @description One solve, wrapped with everything a reviewer needs to accept or refuse it.
         */
        Proposal: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /** Approved At */
            approved_at?: string | null;
            /** Approved By */
            approved_by?: string | null;
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Case Id */
            case_id?: string | null;
            /**
             * Catalog Sha256
             * @default
             */
            catalog_sha256: string;
            /** Catalog Version */
            catalog_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /**
             * Logic Version
             * @default
             */
            logic_version: string;
            /** Missing Documentation */
            missing_documentation?: components["schemas"]["MissingDocumentation"][];
            /** Proposal Id */
            proposal_id: string;
            /** Receipt Hash */
            receipt_hash: string;
            /** Rejected Reason */
            rejected_reason?: string | null;
            rule_coverage?: components["schemas"]["RuleCoverage"] | null;
            /**
             * Rules Engine Version
             * @default
             */
            rules_engine_version: string;
            /**
             * Rules Hash
             * @default
             */
            rules_hash: string;
            /** Rules Version */
            rules_version: string;
            solver_result: components["schemas"]["CodingResponse"];
            /** Solver Version */
            solver_version: string;
            /** @default DRAFT */
            status: components["schemas"]["ProposalStatus"];
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /** Warnings */
            warnings?: components["schemas"]["Warning_"][];
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "DRAFT" | "APPROVED" | "REJECTED" | "EXPORTED";
        /** RejectionRequest */
        RejectionRequest: {
            /** Reason */
            reason: string;
            /** Rejected By */
            rejected_by: string;
        };
        /**
         * RuleCoverage
         * @description How much of the rule set is actually being enforced, on every response that has one.
         *
         *     The API must never imply that unverified rules are enforced. ``enforced_rule_count`` is what
         *     can suppress a position; ``advisory_rule_count`` is what only warns. Under the default
         *     ``UNVERIFIED_RULE_POLICY=warn`` the advisory set is the automatically extracted majority, and
         *     a response carrying a non-zero advisory count also carries a warning saying so.
         */
        RuleCoverage: {
            /**
             * Advisory Rule Count
             * @default 0
             */
            advisory_rule_count: number;
            /**
             * Enforced Rule Count
             * @default 0
             */
            enforced_rule_count: number;
            /** Policy For Unverified Rules */
            policy_for_unverified_rules: string;
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            /**
             * Rules Version
             * @default
             */
            rules_version: string;
            /**
             * Suppressed Unverified Rule Count
             * @default 0
             */
            suppressed_unverified_rule_count: number;
            /**
             * Verified Share
             * @default 0/0
             */
            verified_share: string;
        };
        /**
         * SolveRequest
         * @description ``POST /api/v1/solve`` — clinical entities in, an auditable draft out.
         *
         *     Accepts either the envelope ``{"extraction": {...}, "setting": ...}`` or a bare extraction
         *     posted directly, because ``curl -d @logic/tests/cases/case_001_knee/input.json`` is the
         *     obvious thing to reach for and the case files are bare extractions.
         */
        SolveRequest: {
            /**
             * Case Id
             * @description Caller's identifier for this encounter, echoed onto the proposal.
             */
            case_id?: string | null;
            extraction: components["schemas"]["ClinicalExtraction-Input"];
            /**
             * Setting
             * @description Overrides patient.setting; drives § 6a Minderung.
             */
            setting?: ("ambulant" | "stationaer" | "belegarzt") | null;
        };
        /** Totals */
        Totals: {
            /**
             * Amount Cent Unrounded
             * @default 0
             */
            amount_cent_unrounded: string;
            /**
             * Amount Eur
             * @default 0
             */
            amount_eur: string;
            /**
             * Amount Eur Before Minderung
             * @default 0
             */
            amount_eur_before_minderung: string;
            /**
             * Minderung Applied
             * @default false
             */
            minderung_applied: boolean;
            /**
             * Minderung Rate
             * @default 0
             */
            minderung_rate: string;
            /**
             * Punkte
             * @default 0
             */
            punkte: number;
            /**
             * Punktwert Cent
             * @default 5.82873
             */
            punktwert_cent: string;
            /**
             * Rounding Legal Basis
             * @default
             */
            rounding_legal_basis: string;
            /**
             * Rounding Policy
             * @default ROUND_HALF_UP
             */
            rounding_policy: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VocabularyResponse
         * @description What `GET /api/v1/vocabulary` returns.
         *
         *     Declared as a model rather than a bare dict for one concrete reason: an endpoint with no
         *     OpenAPI schema cannot have a TypeScript client generated for it, so the front end wrote one by
         *     hand and got the shape wrong in three ways — `entity_types` declared as a flat array when the
         *     API returns a mapping keyed by kind, options keyed on `value` rather than `entity_type`, and an
         *     invented `sexes` list. None of it failed a type check on either side.
         *
         *     `entity_types` is a mapping so a UI can group the pickers without re-deriving groups.
         */
        VocabularyResponse: {
            /** Catalog Version */
            catalog_version: string;
            /** Complexities */
            complexities: components["schemas"]["BilingualOption"][];
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Entity Types */
            entity_types: {
                [key: string]: components["schemas"]["EntityTypeOption"][];
            };
            /** Settings */
            settings: components["schemas"]["BilingualOption"][];
            /** Severities */
            severities: components["schemas"]["BilingualOption"][];
        };
        /**
         * Warning_
         * @description A non-fatal finding. Named with a trailing underscore to avoid the builtin.
         */
        Warning_: {
            /**
             * Legal Basis
             * @default
             */
            legal_basis: string;
            /** Message */
            message: string;
            /**
             * Rule Id
             * @default
             */
            rule_id: string;
            /**
             * Severity
             * @default warning
             * @enum {string}
             */
            severity: "info" | "warning" | "error";
            /** Type */
            type: string;
            /** Ziffer */
            ziffer?: string | null;
        };
        /**
         * ZifferResponse
         * @description One catalog position, with the rules that touch it.
         */
        ZifferResponse: {
            /** Annotations */
            annotations?: string[];
            /** Category */
            category?: string | null;
            /** Exclusions Enforced */
            exclusions_enforced?: {
                [key: string]: unknown;
            }[];
            /** Factor Band */
            factor_band?: {
                [key: string]: unknown;
            };
            /** Factor Cap */
            factor_cap?: {
                [key: string]: unknown;
            } | null;
            /**
             * Minderung Exempt
             * @default false
             */
            minderung_exempt: boolean;
            /** Official Text */
            official_text: string;
            /**
             * Provenance
             * @default official
             */
            provenance: string;
            /** Punkte */
            punkte: number;
            /**
             * Rule Coverage
             * @default partial
             */
            rule_coverage: string;
            /** Section */
            section?: string | null;
            /** Section Title */
            section_title?: string | null;
            /**
             * Status
             * @default active
             */
            status: string;
            /**
             * Text Quality
             * @default ok
             */
            text_quality: string;
            /** Ziffer */
            ziffer: string;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog_api_v1_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    catalog_ziffer_api_v1_catalog_ziffer__ziffer__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ziffer: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZifferResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    padnext_audit_api_v1_padnext_audit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PadnextAuditReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_v1_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_v1_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_api_v1_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_exported_api_v1_proposals__proposal_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_api_v1_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_api_v1_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vocabulary_api_v1_vocabulary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VocabularyResponse"];
                };
            };
        };
    };
}
