"""Every schema the engine speaks, re-exported as one namespace.

The modules are split by concern — `case` (the frozen clinical input contract), `facts` (the
symbolic layer), `solver`, `result`, `proposal`, `padnext`, `batch`, `export`, `rules`, `meta` — but callers
import from here, so moving a model between them is not a breaking change.
"""

from app.schemas.api_keys import (
    ApiKeyIssued,
    ApiKeyList,
    ApiKeyRequest,
    ApiKeyRevoked,
    ApiKeySummary,
)
from app.schemas.batch import (
    BatchAggregateSummary,
    BatchAuditAccepted,
    BatchAuditJob,
    BatchAuditJobList,
    BatchAuditJobSummary,
    BatchFileResult,
    BatchFileStatus,
    BatchJobStatus,
)
from app.schemas.case import (
    ClinicalExtraction,
    Consultation,
    Diagnosis,
    Examination,
    JustificationFactor,
    LabTest,
    Patient,
    Procedure,
    SolveRequest,
)
from app.schemas.common import (
    Complexity,
    Dec,
    RuleCoverage,
    Setting,
    Severity,
    Sex,
    ValidationViolation,
    Warning_,
)
from app.schemas.export import (
    EXPORT_FORMAT_VERSION,
    AuditEventRecord,
    DecisionRecord,
    EngineIdentity,
    ExportRequest,
    ProposalExport,
)
from app.schemas.facts import (
    AnalogRequest,
    BlockedCode,
    ClinicalAct,
    CodeCandidate,
    Conflict,
    ProofStep,
    RulesResult,
)
from app.schemas.meta import (
    BilingualOption,
    CatalogResponse,
    ComplexityRef,
    EntityTypeOption,
    HealthResponse,
    LabelledOption,
    SolverHealth,
    VocabularyResponse,
    ZifferResponse,
)
from app.schemas.padnext import (
    BEHANDLUNGSART_LABEL,
    BEHANDLUNGSART_TO_SETTING,
    PadnextAuditedPosition,
    PadnextAuditReport,
    PadnextCase,
    PadnextDelivery,
    PadnextFinding,
    PadnextInvoice,
    PadnextPosition,
    PositionBucket,
)
from app.schemas.proposal import (
    ApprovalRequest,
    Proposal,
    ProposalList,
    ProposalStatus,
    RejectionRequest,
)
from app.schemas.result import (
    AuditTrail,
    AuditTrailEntry,
    Coding,
    CodingResponse,
    InvoiceLine,
    Totals,
)
from app.schemas.rules import (
    ReviewableRule,
    ReviewStatus,
    RuleKind,
    RuleReviewQueue,
    RuleReviewRequest,
    RuleReviewResult,
)
from app.schemas.solver import (
    AnalogDecision,
    FactorDecision,
    GroundingStats,
    MissingDocumentation,
    OptimizationResult,
)

__all__ = [
    "BEHANDLUNGSART_LABEL",
    "BEHANDLUNGSART_TO_SETTING",
    "EXPORT_FORMAT_VERSION",
    "AnalogDecision",
    "AnalogRequest",
    "ApiKeyIssued",
    "ApiKeyList",
    "ApiKeyRequest",
    "ApiKeyRevoked",
    "ApiKeySummary",
    "ApprovalRequest",
    "AuditEventRecord",
    "AuditTrail",
    "AuditTrailEntry",
    "BatchAggregateSummary",
    "BatchAuditAccepted",
    "BatchAuditJob",
    "BatchAuditJobList",
    "BatchAuditJobSummary",
    "BatchFileResult",
    "BatchFileStatus",
    "BatchJobStatus",
    "BilingualOption",
    "BlockedCode",
    "CatalogResponse",
    "ClinicalAct",
    "ClinicalExtraction",
    "CodeCandidate",
    "Coding",
    "CodingResponse",
    "Complexity",
    "ComplexityRef",
    "Conflict",
    "Consultation",
    "Dec",
    "DecisionRecord",
    "Diagnosis",
    "EngineIdentity",
    "EntityTypeOption",
    "ExportRequest",
    "Examination",
    "FactorDecision",
    "GroundingStats",
    "HealthResponse",
    "InvoiceLine",
    "JustificationFactor",
    "LabTest",
    "LabelledOption",
    "MissingDocumentation",
    "OptimizationResult",
    "PadnextAuditReport",
    "PadnextAuditedPosition",
    "PadnextCase",
    "PadnextDelivery",
    "PadnextFinding",
    "PadnextInvoice",
    "PadnextPosition",
    "PositionBucket",
    "Patient",
    "Procedure",
    "Proposal",
    "ProposalExport",
    "ProposalList",
    "ProposalStatus",
    "ProofStep",
    "RejectionRequest",
    "ReviewStatus",
    "ReviewableRule",
    "RuleCoverage",
    "RuleKind",
    "RuleReviewQueue",
    "RuleReviewRequest",
    "RuleReviewResult",
    "RulesResult",
    "Setting",
    "Severity",
    "Sex",
    "SolveRequest",
    "SolverHealth",
    "Totals",
    "ValidationViolation",
    "VocabularyResponse",
    "Warning_",
    "ZifferResponse",
]
