"""Who the caller says it is.

The engine still authenticates nobody, and this module does not change that. What it changes is
that the audit log can now say *something* other than `anonymous`: the Next.js application in front
of this service holds a Better Auth session, and it forwards the authenticated user's id in
`X-User-ID` on every call it proxies. This reads that header and turns it into the `actor` string
`app.services.proposal_store` writes.

**The header is asserted, not proven.** Nothing here verifies a signature, and it must not be
mistaken for authentication. What makes it worth recording is the deployment shape rather than the
header itself: `ENGINE_BASE_URL` is server-only in the web app (it is deliberately not
`NEXT_PUBLIC_`), the engine is not published to the browser in
`infra/docker/docker-compose.yml`, and every call therefore arrives from one trusted proxy that
sets the header from a session cookie it verified. An engine reachable from the open internet would
need a real token — a Better Auth JWT the engine verifies — and this module is the seam where that
goes. Until then the honest statement is: this is who the proxy said it was.

**Only the id travels, never the email or the name.** The audit log is a compliance record on a
service that handles clinical data, and an opaque user id is enough to answer "who did this" by
joining to Better Auth's own `user` table. Putting a person's address into an append-only log —
which by construction cannot be corrected or deleted — would be a retention decision nobody made.

The dependency takes a `Request` rather than declaring a `Header` parameter, and that is not an
accident: a declared header would appear in the committed OpenAPI document and become part of a
contract the frontend generates types from. `X-User-ID` is transport between two of our own tiers,
not part of the published API.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import Depends, Request

from app.services.proposal_store import ANONYMOUS_ACTOR

#: What the Next.js proxy sets. Lower-case because Starlette's header lookup is case-insensitive
#: and this is the form that shows up in a log.
USER_ID_HEADER = "x-user-id"

#: `audit_events.actor`, `proposals.created_by` and `batch_jobs.created_by` are all `String(256)`.
#: A longer value is truncated here rather than at the database, where SQLite would silently store
#: it whole and Postgres would raise on a write that is otherwise fine.
MAX_ACTOR_LENGTH = 256


def _sanitise(raw: str | None) -> str:
    """A header value fit to be written into an append-only log, or the anonymous marker.

    Control characters are stripped rather than escaped. A user id is opaque and generated by
    Better Auth, so anything in this class is either a client bug or an attempt to forge log lines
    with an embedded newline; neither is a value worth preserving faithfully.
    """
    if raw is None:
        return ANONYMOUS_ACTOR
    cleaned = "".join(character for character in raw if character.isprintable()).strip()
    if not cleaned:
        return ANONYMOUS_ACTOR
    return cleaned[:MAX_ACTOR_LENGTH]


def request_actor(request: Request) -> str:
    """The actor to attribute this request to. `anonymous` when the header is absent or empty.

    Absent is the normal case for a direct call — `curl`, the test suite, `/docs` — and it must stay
    usable: this endpoint set has no login and refusing an unattributed read would break every one
    of those callers for no gain in trustworthiness.
    """
    return _sanitise(request.headers.get(USER_ID_HEADER))


#: What path functions annotate with. `Annotated[...]` rather than a default value so the parameter
#: stays positional-friendly and FastAPI keeps it out of the OpenAPI document.
RequestActor = Annotated[str, Depends(request_actor)]


__all__ = ["MAX_ACTOR_LENGTH", "USER_ID_HEADER", "RequestActor", "request_actor"]
