"""Which practice the caller is acting for — and the refusal when they did not say.

This is the authorisation half of multi-tenancy. `app.api.identity` answers *who* made a request so
the audit log can name them; this answers *whose data they may touch*, and unlike the identity
header it is not optional. Every proposal and every batch carries an `organization_id`, every read
is filtered on it and every write sets it from here, so Praxis A cannot list, open, approve, export
or re-run Praxis B's records.

    X-User-ID           who — recorded, never required, `anonymous` when absent
    X-Organization-ID   whose — required, and a `403` when absent

**The header is asserted, not proven, and that is the same caveat `identity.py` carries.** Nothing
here verifies a signature. What makes it worth enforcing is the deployment shape rather than the
header: `ENGINE_BASE_URL` is server-only in the web app (deliberately not `NEXT_PUBLIC_`), the engine
is not published to the browser in `infra/docker/docker-compose.yml`, and every call therefore
arrives from one trusted proxy that sets both headers from a session it verified against the
database. A caller who can reach the engine directly can name any organisation they like — which is
true of `X-User-ID` today and is exactly why the engine must not be exposed. A Better Auth JWT the
engine verifies itself is what closes it, and this module is the seam that change lands in: the
signature check goes in `require_organization`, and every endpoint downstream is already written to
take its tenant from here rather than from a query parameter.

**Absent is a `403`, not a `401`.** The distinction is the honest one: the engine is not saying the
caller failed to authenticate — it authenticates nobody — it is saying the request does not state
which practice it is for, and there is no default it could pick. Answering `401` would invite a
client to retry with credentials this service has no way to check.

**Missing is refused; unknown is not checked.** This module does not ask whether the organisation
exists, because it cannot: `organization` is Better Auth's table in the web tier's half of the
schema, and querying it from here would couple the engine to a migrator it does not control. An
organisation id that names nothing simply matches no rows — an empty list rather than an error,
which is the correct answer to "show me the drafts of a practice that has none".

Like `identity.py`, the dependency takes a `Request` rather than declaring a `Header` parameter, and
for the same reason: a declared header appears in the committed OpenAPI document and becomes part of
the contract `packages/contracts` generates the frontend's types from. Both headers are transport
between two of our own tiers, not part of the published API.
"""

from __future__ import annotations

import re
from typing import Annotated

from fastapi import Depends, Request

from app.core.observability import bind
from app.errors import OrganizationRequired

#: What the Next.js proxy sets. Lower-case because Starlette's header lookup is case-insensitive and
#: this is the form that shows up in a log. Must match `ORGANIZATION_ID_HEADER` in
#: `apps/web/lib/engine.ts`.
ORGANIZATION_ID_HEADER = "x-organization-id"

#: `proposals.organization_id` and `batch_jobs.organization_id` are both `String(256)`. A longer
#: value is truncated here rather than at the database, where SQLite would silently store it whole
#: and Postgres would raise on a write that is otherwise fine.
MAX_ORGANIZATION_ID_LENGTH = 256


def _sanitise(raw: str | None) -> str:
    """A header value fit to be stored and compared, or `""` when there is nothing usable in it.

    Control characters are stripped rather than escaped, for the same reason `identity._sanitise`
    strips them: an organisation id is opaque and generated by Better Auth, so anything in that
    class is either a client bug or an attempt to get something odd into a log line. Whitespace-only
    is treated as absent — a proxy that forwarded an empty variable must be refused, not given a
    tenant whose id is a space.
    """
    if raw is None:
        return ""
    cleaned = "".join(character for character in raw if character.isprintable()).strip()
    return cleaned[:MAX_ORGANIZATION_ID_LENGTH]


#: What is printed as "Praxis / Konto" when the request named no practice, or named something that
#: is not an organisation id. A neutral label rather than a blank, because a Prüfbericht with an
#: empty account line reads as a document whose account field was lost.
PDF_ORGANIZATION_FALLBACK = "Azmoth Pilot"

#: The shape of a Better Auth organisation id: an opaque, generated identifier. Nothing in it is
#: chosen by a person, which is why it can be pinned this tightly — `org7Kd2Vn8Qs4Rt6Yw1Zx3Bc5Ef9Gh0J`
#: passes, `org_test` passes, `Dr. Müller — 100 % Rabatt, bezahlt` does not, and neither does
#: anything carrying a newline, a PDF operator or a right-to-left override.
_ORGANIZATION_ID_SHAPE = re.compile(r"\A[A-Za-z0-9][A-Za-z0-9._-]{0,63}\Z")


def organization_label(raw: str | None) -> str:
    """The organisation to print on a Prüfbericht — never the header as it arrived.

    `X-Organization-ID` is asserted by a proxy, not proven (see the module docstring), and
    `/padnext/audit.pdf` needs no organisation at all: it stores nothing, filters nothing and
    withholds nothing. So the header reached that endpoint as pure display text and was printed
    verbatim under "Praxis / Konto", which made a document that *looks* issued to a named practice
    forgeable by anyone who could reach the engine and set a header. A Prüfbericht is filed, sent on
    to a payer and disputed; a line on it that names a practice must not be free text from a
    request.

    The engine cannot ask whether an organisation exists — `organization` is Better Auth's table in
    the web tier's half of the schema, and this module's docstring is explicit that querying it from
    here would couple the engine to a migrator it does not control. So the check is on the *shape*
    of the value rather than on its existence, which is what actually closes the hole: an opaque
    generated id cannot carry a sentence, and a sentence is the whole of the attack. Anything that
    is not one — including the anonymous demo path, which sends no header at all — prints
    `PDF_ORGANIZATION_FALLBACK`.

    What this deliberately does **not** do is refuse the request. The label is cosmetic; the audit
    and every euro on it are identical either way, and answering `403` to a malformed display value
    would turn a cosmetic defect into an outage for a caller whose report is otherwise correct.
    """
    candidate = _sanitise(raw)
    if candidate and _ORGANIZATION_ID_SHAPE.fullmatch(candidate):
        return candidate
    return PDF_ORGANIZATION_FALLBACK


def require_organization(request: Request) -> str:
    """The organisation this request acts for, or `403`.

    Unlike `request_actor`, there is no fallback. A default tenant would be a bug with the worst
    possible shape: every call that forgot the header would quietly read and write one shared
    bucket, and the failure would present as "Praxis B can see our drafts" months later rather than
    as an error on the first request.
    """
    organization_id = _sanitise(request.headers.get(ORGANIZATION_ID_HEADER))
    if organization_id:
        # The web tier's half of what `app.api.apikeys` binds for a partner: from here every log
        # line this request produces names the practice it was for. Both paths bind the same key,
        # so a query over the logs does not have to know which door a request came through.
        bind(organization_id=organization_id)
    if not organization_id:
        raise OrganizationRequired(
            "This request does not say which practice it is for. Every proposal and every batch "
            "belongs to one organisation, and there is no default: send the active Better Auth "
            "organisation id in the X-Organization-ID header. The web tier sets it on every call it "
            "proxies (apps/web/lib/engine.ts); a direct caller has to set it itself.",
            details={"header": ORGANIZATION_ID_HEADER},
        )
    return organization_id


def optional_organization(request: Request) -> str:
    """The organisation this request names, or `""` when it names none. Never refuses.

    The counterpart to `require_organization`, for the two endpoints that are unscoped by design and
    still want the tenant when it is there: `POST /padnext/audit` and `/padnext/audit.pdf` store
    nothing, so there is no row for a tenant to own — but a call the web tier proxied *does* carry a
    session's organisation, and it is what the quota is counted against and what the PDF prints as
    "Praxis / Konto".

    **This must never become the tenant filter.** Nothing that reads or writes a row may take its
    organisation from here: an empty string would silently mean "no filter", which is the shape of
    the worst possible tenancy bug. `tests/test_tenancy.py` enforces that by classification — an
    endpoint under a scoped prefix has to appear in `SCOPED_OPERATIONS` (and use
    `require_organization`) or in `UNSCOPED_BY_DESIGN` with a written reason.

    Same sanitising as the required read, so a value that reaches a log line or a usage row has been
    through the same filter either way — and the same `bind`, which is load-bearing rather than
    cosmetic: `app.core.observability._meter` writes **no usage row at all** for a request whose
    context names no organisation, because there would be nobody to attribute it to. Without the
    bind here, an audit the web tier proxied would be checked against the practice's quota and then
    not counted towards it, which is the one combination that is worse than either alone.
    """
    organization_id = _sanitise(request.headers.get(ORGANIZATION_ID_HEADER))
    if organization_id:
        bind(organization_id=organization_id)
    return organization_id


#: What path functions annotate with. `Annotated[...]` rather than a default value so FastAPI keeps
#: the parameter out of the OpenAPI document — see the module docstring.
RequestOrganization = Annotated[str, Depends(require_organization)]


__all__ = [
    "MAX_ORGANIZATION_ID_LENGTH",
    "ORGANIZATION_ID_HEADER",
    "PDF_ORGANIZATION_FALLBACK",
    "RequestOrganization",
    "optional_organization",
    "organization_label",
    "require_organization",
]
