"""Which practice the caller is acting for — and the refusal when they did not say.

This is the authorisation half of multi-tenancy. `app.api.identity` answers *who* made a request so
the audit log can name them; this answers *whose data they may touch*, and unlike the identity
header it is not optional. Every proposal and every batch carries an `organization_id`, every read
is filtered on it and every write sets it from here, so Praxis A cannot list, open, approve, export
or re-run Praxis B's records.

    X-User-ID           who — recorded, never required, `anonymous` when absent
    X-Organization-ID   whose — required, and a `403` when absent

**The header is asserted, not proven, and that is the same caveat `identity.py` carries.** Nothing
here verifies a signature. What makes it worth enforcing is the deployment shape rather than the
header: `ENGINE_BASE_URL` is server-only in the web app (deliberately not `NEXT_PUBLIC_`), the engine
is not published to the browser in `infra/docker/docker-compose.yml`, and every call therefore
arrives from one trusted proxy that sets both headers from a session it verified against the
database. A caller who can reach the engine directly can name any organisation they like — which is
true of `X-User-ID` today and is exactly why the engine must not be exposed. A Better Auth JWT the
engine verifies itself is what closes it, and this module is the seam that change lands in: the
signature check goes in `require_organization`, and every endpoint downstream is already written to
take its tenant from here rather than from a query parameter.

**Absent is a `403`, not a `401`.** The distinction is the honest one: the engine is not saying the
caller failed to authenticate — it authenticates nobody — it is saying the request does not state
which practice it is for, and there is no default it could pick. Answering `401` would invite a
client to retry with credentials this service has no way to check.

**Missing is refused; unknown is not checked.** This module does not ask whether the organisation
exists, because it cannot: `organization` is Better Auth's table in the web tier's half of the
schema, and querying it from here would couple the engine to a migrator it does not control. An
organisation id that names nothing simply matches no rows — an empty list rather than an error,
which is the correct answer to "show me the drafts of a practice that has none".

Like `identity.py`, the dependency takes a `Request` rather than declaring a `Header` parameter, and
for the same reason: a declared header appears in the committed OpenAPI document and becomes part of
the contract `packages/contracts` generates the frontend's types from. Both headers are transport
between two of our own tiers, not part of the published API.
"""

from __future__ import annotations

from typing import Annotated

from fastapi import Depends, Request

from app.errors import OrganizationRequired

#: What the Next.js proxy sets. Lower-case because Starlette's header lookup is case-insensitive and
#: this is the form that shows up in a log. Must match `ORGANIZATION_ID_HEADER` in
#: `apps/web/lib/engine.ts`.
ORGANIZATION_ID_HEADER = "x-organization-id"

#: `proposals.organization_id` and `batch_jobs.organization_id` are both `String(256)`. A longer
#: value is truncated here rather than at the database, where SQLite would silently store it whole
#: and Postgres would raise on a write that is otherwise fine.
MAX_ORGANIZATION_ID_LENGTH = 256


def _sanitise(raw: str | None) -> str:
    """A header value fit to be stored and compared, or `""` when there is nothing usable in it.

    Control characters are stripped rather than escaped, for the same reason `identity._sanitise`
    strips them: an organisation id is opaque and generated by Better Auth, so anything in that
    class is either a client bug or an attempt to get something odd into a log line. Whitespace-only
    is treated as absent — a proxy that forwarded an empty variable must be refused, not given a
    tenant whose id is a space.
    """
    if raw is None:
        return ""
    cleaned = "".join(character for character in raw if character.isprintable()).strip()
    return cleaned[:MAX_ORGANIZATION_ID_LENGTH]


def require_organization(request: Request) -> str:
    """The organisation this request acts for, or `403`.

    Unlike `request_actor`, there is no fallback. A default tenant would be a bug with the worst
    possible shape: every call that forgot the header would quietly read and write one shared
    bucket, and the failure would present as "Praxis B can see our drafts" months later rather than
    as an error on the first request.
    """
    organization_id = _sanitise(request.headers.get(ORGANIZATION_ID_HEADER))
    if not organization_id:
        raise OrganizationRequired(
            "This request does not say which practice it is for. Every proposal and every batch "
            "belongs to one organisation, and there is no default: send the active Better Auth "
            "organisation id in the X-Organization-ID header. The web tier sets it on every call it "
            "proxies (apps/web/lib/engine.ts); a direct caller has to set it itself.",
            details={"header": ORGANIZATION_ID_HEADER},
        )
    return organization_id


#: What path functions annotate with. `Annotated[...]` rather than a default value so FastAPI keeps
#: the parameter out of the OpenAPI document — see the module docstring.
RequestOrganization = Annotated[str, Depends(require_organization)]


__all__ = [
    "MAX_ORGANIZATION_ID_LENGTH",
    "ORGANIZATION_ID_HEADER",
    "RequestOrganization",
    "require_organization",
]
