"""batch PADnext audit jobs and their files.

Revision ID: 0002_batch_audit
Revises: 0001_proposals_audit
Create Date: 2026-08-22

Two tables behind `POST /api/v1/padnext/batch`. `batch_jobs` is one upload of many deliveries and
the roll-up across them; `batch_files` is one delivery inside it and the report it produced. See
`app/db/models.py` for what each column is for and `app/schemas/batch.py` for why the roll-up keeps
the three honest buckets separate instead of reducing them to a single "at risk" figure.

Written by hand rather than autogenerated, and checked against `Base.metadata` by
`tests/test_db_persistence.py::test_the_migration_and_the_models_describe_the_same_schema`. The
same two caveats as `0001` apply and are the reason this file does not simply take autogenerate's
output: it emits `postgresql.JSONB(astext_type=Text())` with `Text` unqualified and not imported,
and it names revisions with a hex hash where `alembic history` is something a human reads during an
incident.

**What this migration deliberately does NOT do:** add a `CHECK` constraint on either `status`
column. The allowed values live in `BatchJobStatus` and `BatchFileStatus`, and a database-level
enumeration of them would have to be migrated in lockstep with the Python one for no gain — unlike
`audit_events`, where the database is the second line of defence for a property (append-only) the
application could violate by accident, nothing writes these columns except the one service that
owns them.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0002_batch_audit"
down_revision: str | None = "0001_proposals_audit"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _json() -> sa.types.TypeEngine:
    """JSONB on Postgres, portable JSON elsewhere — the variant `app/db/base.py` declares.

    Spelled out here rather than imported from the app for the same reason as in `0001`: a
    migration has to keep describing the schema it created even after the models move on.
    """
    return sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")


def upgrade() -> None:
    op.create_table(
        "batch_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("aggregate_summary_json", _json(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        # Unique: `batch_id` is the handle the frontend polls, so two rows answering to one id
        # would make "the batch that was uploaded" ambiguous.
        batch_op.create_index(batch_op.f("ix_batch_jobs_batch_id"), ["batch_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_batch_jobs_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_batch_jobs_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "batch_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("batch_job_id", sa.Uuid(), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("report_json", _json(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        # CASCADE for the same reason as `audit_events`: a file row pointing at a batch that no
        # longer exists is a report nobody can interpret. No code path here deletes a batch.
        sa.ForeignKeyConstraint(["batch_job_id"], ["batch_jobs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("batch_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_batch_files_batch_job_id"), ["batch_job_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_batch_files_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_batch_files_batch_job_id_filename", ["batch_job_id", "filename"], unique=False
        )


def downgrade() -> None:
    """Drops both tables.

    Unlike `0001`'s downgrade this destroys nothing a human decided: a batch job is the record of a
    computation, and re-uploading the same files reproduces it. It still throws away every report,
    so it is a development and test path, not an operational one.
    """
    with op.batch_alter_table("batch_files", schema=None) as batch_op:
        batch_op.drop_index("ix_batch_files_batch_job_id_filename")
        batch_op.drop_index(batch_op.f("ix_batch_files_status"))
        batch_op.drop_index(batch_op.f("ix_batch_files_batch_job_id"))
    op.drop_table("batch_files")

    with op.batch_alter_table("batch_jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_batch_jobs_status_created_at")
        batch_op.drop_index(batch_op.f("ix_batch_jobs_status"))
        batch_op.drop_index(batch_op.f("ix_batch_jobs_batch_id"))
    op.drop_table("batch_jobs")
