"""rule reviews — a billing expert's verdict on a machine-extracted rule.

Revision ID: 0003_rule_reviews
Revises: 0002_batch_audit
Create Date: 2026-08-22

One table behind `GET /api/v1/rules/review-queue` and `POST /api/v1/rules/{rule_id}/review`. It is
an **overlay** on `data/rules/*.csv`, not a copy of them: 859 of the 894 constraint rules were
extracted from the GOÄ's prose automatically, and this is where a human's decision about one of
them is recorded so that `RuleStore.with_reviews` can merge it at load time. The CSVs stay
untouched — they are versioned source data, a PR that changes them needs a second approver
(`CONTRIBUTING.md`), and an API that wrote to them would route around exactly that control.

**No foreign key, deliberately.** `rule_id` names a row in a CSV file, which no database constraint
can reach. That means a review can outlive the rule it refers to — if a future data change deletes
`excl_auto_30_4`, its row here becomes inert rather than invalid. That is the right failure: the
merge simply never finds it, and the record of somebody's decision is not silently destroyed by a
data import.

Written by hand for the same two reasons as `0001` and `0002`: autogenerate emits
`postgresql.JSONB(astext_type=Text())` with `Text` unimported (not relevant here — there is no JSON
column — but the habit is), and it names revisions with a hex hash where `alembic history` is
something a human reads during an incident.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_rule_reviews"
down_revision: str | None = "0002_batch_audit"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "rule_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("reviewed_by", sa.String(length=256), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("rule_reviews", schema=None) as batch_op:
        # Unique: the merge resolves `rule_id -> status`, so two rows answering to one id would make
        # a rule's effective verification state depend on which row was read first.
        batch_op.create_index(batch_op.f("ix_rule_reviews_rule_id"), ["rule_id"], unique=True)
        batch_op.create_index(batch_op.f("ix_rule_reviews_status"), ["status"], unique=False)
        batch_op.create_index(
            "ix_rule_reviews_status_rule_id", ["status", "rule_id"], unique=False
        )


def downgrade() -> None:
    """Drops the table, and with it every verification decision a reviewer made.

    Worth stating plainly because it is not like `0002`'s downgrade: a batch export can be
    regenerated by re-uploading the files, and a rule review cannot be regenerated by anything
    except a person reading the GOÄ again. Present because a migration without a downgrade cannot
    be tested — `alembic downgrade base` then `upgrade head` is how the drift test proves this file
    and `app/db/models.py` agree — and not because running it against a working database is
    something anyone should do.
    """
    with op.batch_alter_table("rule_reviews", schema=None) as batch_op:
        batch_op.drop_index("ix_rule_reviews_status_rule_id")
        batch_op.drop_index(batch_op.f("ix_rule_reviews_status"))
        batch_op.drop_index(batch_op.f("ix_rule_reviews_rule_id"))
    op.drop_table("rule_reviews")
