"""Temporal catalog routing: auditing an invoice against the fee schedule it was written under.

A GOÄ position is not a constant. Ziffer 20 did not exist in 1996, and Ziffer 5 has been worth
different Punktzahlen in different editions — so an invoice from one era priced against another
era's catalog produces exact arithmetic on the wrong law. `data/catalogs/` therefore holds one
directory per edition and `load_catalog(catalog_version=...)` chooses one.

These tests are what make the routing claim falsifiable. Three layers, and they fail for different
reasons on purpose:

    routing     the right directory is opened, and an unknown edition is refused rather than
                quietly served from the default
    solving     Clingo cannot bill a position the routed edition does not contain, and prices the
                positions it does contain at that edition's Punktzahl
    identity    the same bytes audited under two editions produce two receipt hashes — including
                when the two editions agree on every number, because the receipt covers *which*
                catalog answered, not only what it said

`goae_current` is the real official snapshot; the four era directories are synthetic fixtures
generated by `scripts/make_temporal_fixtures.py` (see `data/catalogs/README.md`). Only the
fixtures are asserted on here — the official snapshot has its own identity suite in
`tests/test_catalog_snapshot_identity.py`, and pinning fixture Punktzahlen there would be claiming
they mean something.

Nothing here needs the Soufflé binary: `audit_delivery` takes `souffle_run` as an argument, so the
rules stage is stubbed to confirm everything it is handed. That is deliberate rather than
convenient — a stub that confirms every position means a position that is *not* charged was
dropped by the catalog, which is exactly the variable under test.
"""

from __future__ import annotations

import importlib.util
from decimal import Decimal

import pytest

from app.catalog import (
    CatalogError,
    CatalogNotFoundError,
    available_catalog_versions,
    load_catalog,
    resolve_catalog_dir,
)
from app.catalog.catalog_loader import catalog_files
from app.config import CATALOG_FILENAME, DEFAULT_CATALOG_VERSION, ENGINE_DIR
from app.padnext import audit_delivery, read_delivery
from app.schemas import RulesResult
from app.services.pipeline import Pipeline
from app.solvers.clingo_solver import ClingoError, ClingoSolver
from tests.conftest import make_extraction, one_act_per_ziffer

# ------------------------------------------------------------------------------------------
# what each edition is supposed to be
# ------------------------------------------------------------------------------------------

#: The temporal differences the fixtures exist to prove, as data rather than as prose. Punkte on
#: Ziffer 5 is the "base rate" the multi-catalog brief varies: money here is
#: `Punkte × Punktwert × Faktor` (§ 5 Abs. 1 GOÄ), so a GOÄ catalog has no euro column to move.
ERAS = {
    "goae_1996": {"ziffer_5_punkte": 100, "has_20": False, "novel": None},
    "goae_2012": {"ziffer_5_punkte": 125, "has_20": True, "novel": None},
    "goae_2026_current": {"ziffer_5_punkte": 150, "has_20": True, "novel": "99"},
    "goae_neu_draft": {"ziffer_5_punkte": 150, "has_20": True, "novel": "999"},
}

OLDEST = "goae_1996"
CURRENT = "goae_2026_current"
DRAFT = "goae_neu_draft"


@pytest.fixture(scope="module")
def catalogs() -> dict:
    """Every era fixture, loaded once. `load_catalog` is cached per edition, so this is cheap."""
    return {version: load_catalog(catalog_version=version) for version in ERAS}


# ------------------------------------------------------------------------------------------
# a synthetic PADnext delivery, built here so the era under test decides the outcome
# ------------------------------------------------------------------------------------------

#: One position per line: (positionsnr, ziffer, faktor, gesamtbetrag). `gesamtbetrag` is what the
#: file *claims*; the audit recomputes it from whichever catalog it was handed, which is the point.
POSITION = '''    <goziffer positionsnr="{nr}" go="GOÄ" ziffer="{ziffer}">
      <datum>2019-03-11</datum>
      <anzahl>1</anzahl>
      <text>Synthetische Position {ziffer}</text>
      <faktor>{faktor}</faktor>
      <gesamtbetrag>{betrag}</gesamtbetrag>
    </goziffer>'''


def padnext_xml(*positions: tuple[str, str, str, str]) -> bytes:
    """A bare `*_padx.xml` payload — what `read_delivery` accepts without a container.

    Hand-written and minimal on purpose: a subset of the PADneXt 2.12 shape with no patient
    identity in it at all, because none is parsed and none should exist in a fixture.
    """
    body = "\n".join(
        POSITION.format(nr=nr, ziffer=ziffer, faktor=faktor, betrag=betrag)
        for nr, ziffer, faktor, betrag in positions
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!-- SYNTHETIC. No real patient, no real practice, no real invoice. -->
<rechnungen anzahl="1" xmlns="http://padinfo.de/ns/pad">
  <nachrichtentyp version="02.12">ADL</nachrichtentyp>
  <rechnungsersteller><name>Musterpraxis (synthetisch)</name></rechnungsersteller>
  <rechnung id="SYNTH-TEMPORAL-0001" aisrechnungsnr="RG-TEMPORAL-1">
    <abrechnungsfall>
      <behandlungsart>0</behandlungsart>
      <vertragsart>1</vertragsart>
      <positionen posanzahl="{len(positions)}">
{body}
      </positionen>
    </abrechnungsfall>
  </rechnung>
</rechnungen>
""".encode("utf-8")


#: An invoice from 2019 charging a consultation (5) and a group session (20). Ziffer 20 is the
#: temporal variable: it exists in 2012 and later, and not in 1996.
INVOICE_5_AND_20 = padnext_xml(("1", "5", "2.3", "20.11"), ("2", "20", "2.3", "24.13"))

#: Only positions every era shares, for the tests that must isolate catalog *identity* from any
#: difference in the answer.
INVOICE_5_ONLY = padnext_xml(("1", "5", "2.3", "20.11"))


def confirm_everything(extraction, bridge, proposed_factors=None) -> RulesResult:
    """A `souffle_run` stand-in that confirms every candidate it is given.

    Deliberately maximally permissive: with the rules stage confirming everything, any position
    the audit still refuses was refused by the catalog. Note that it cannot confirm what it is
    never handed — `build_audit_input` proposes every claimed GOÄ position regardless of the
    catalog, so Ziffer 20 *is* offered here even under 1996.
    """
    proposed = list(bridge.candidates)
    return RulesResult(proposed=proposed, billable=[c.ziffer for c in proposed])


def audit(body: bytes, catalog_version: str, rules, settings):
    """Read the delivery and audit it against one edition."""
    delivery, read_findings = read_delivery(body, source_name=f"{catalog_version}.xml")
    return audit_delivery(
        delivery,
        catalog=load_catalog(catalog_version=catalog_version),
        rules=rules,
        souffle_run=confirm_everything,
        read_findings=read_findings,
        settings=settings,
    )


def row(report, ziffer: str):
    return next(p for p in report.positions if p.ziffer == ziffer)


# ==========================================================================================
# 1. routing — the right directory, or a refusal
# ==========================================================================================


def test_the_default_edition_is_the_official_snapshot():
    """The fixtures live beside the real catalog, so "which one is the default" is load-bearing.

    A fixture becoming the process default would replace the fee schedule the engine bills with,
    and every other test in the suite would still pass.
    """
    catalog = load_catalog()

    assert DEFAULT_CATALOG_VERSION == "goae_current"
    assert catalog.routed_version == "goae_current"
    assert not catalog.is_synthetic
    assert len(catalog.ziffern) >= 2000


def test_every_era_fixture_is_present_and_admits_that_it_is_a_fixture():
    available = available_catalog_versions()

    assert set(ERAS) <= set(available), f"missing era fixtures: {sorted(set(ERAS) - set(available))}"
    for version in ERAS:
        catalog = load_catalog(catalog_version=version)
        assert catalog.is_synthetic, f"{version} must declare itself synthetic"
        assert "SYNTHETIC" in catalog.source.legal_status
        assert all(z.provenance == "illustrative" for z in catalog.ziffern.values())


@pytest.mark.parametrize("version", sorted(ERAS))
def test_an_edition_resolves_to_its_own_directory(version):
    """Routing in full: the edition name is the directory name, and the overrides file that is
    applied comes from the same directory — never from another era's."""
    directory = resolve_catalog_dir(version)
    catalog_path, overrides_path = catalog_files(version)

    assert directory.name == version
    assert directory.parent.name == "catalogs"
    assert catalog_path == directory / CATALOG_FILENAME
    assert overrides_path.parent == directory
    assert load_catalog(catalog_version=version).path == catalog_path


@pytest.mark.parametrize("version,spec", sorted(ERAS.items()))
def test_the_eras_differ_exactly_where_they_are_meant_to(catalogs, version, spec):
    catalog = catalogs[version]

    assert catalog.get("5").punkte == spec["ziffer_5_punkte"], "Ziffer 5 carries the era's rate"
    assert catalog.has("20") is spec["has_20"], "Ziffer 20 is the temporal existence test"
    for novel in ("99", "999"):
        assert catalog.has(novel) is (novel == spec["novel"]), (
            f"{novel} may only exist in the edition that introduced it"
        )
    # Structurally identical: an era differs in its positions, never in its § 5 bands or Punktwert.
    assert catalog.punktwert_cent == Decimal("5.82873")
    assert catalog.factor_band("5").max == Decimal("3.5")


def test_ziffer_5_gets_dearer_with_every_edition(catalogs):
    """The "base rate" progression, read as money: 100 → 125 → 150 Punkte at the Einfachsatz."""
    einfachsatz = {
        version: catalog.get("5").punkte * catalog.punktwert_cent / 100
        for version, catalog in catalogs.items()
    }

    assert einfachsatz["goae_1996"] < einfachsatz["goae_2012"] < einfachsatz[CURRENT]
    assert einfachsatz[CURRENT] == einfachsatz[DRAFT], "the draft only renumbers a position"


# ==========================================================================================
# 2. Test Case D — a non-existent edition is an error, not a fallback
# ==========================================================================================


def test_an_unknown_edition_is_refused_and_never_falls_back():
    with pytest.raises(CatalogNotFoundError) as exc:
        load_catalog(catalog_version="goae_1800")

    message = str(exc.value)
    assert "goae_1800" in message
    assert DEFAULT_CATALOG_VERSION in message, "the message must list what does exist"


def test_the_refusal_is_also_a_value_error_and_still_a_catalog_error():
    """Both bases are part of the contract: a route handler may treat a bad edition as a bad
    argument, and every existing `except CatalogError` around catalog loading keeps working."""
    for expected in (ValueError, CatalogError):
        with pytest.raises(expected):
            load_catalog(catalog_version="goae_1800")


@pytest.mark.parametrize(
    "version", ["../goae_current", "goae_current/", "/etc", ".hidden", "goae current"]
)
def test_an_edition_name_that_is_not_a_directory_name_is_refused(version):
    """The edition may one day arrive as a query parameter, so `..` must not resolve at all."""
    with pytest.raises(CatalogNotFoundError):
        resolve_catalog_dir(version)


def test_an_edition_directory_without_a_catalog_file_says_so(tmp_path):
    """A half-populated edition is a likelier mistake than a typo, and gets its own message."""
    (tmp_path / "goae_2030").mkdir()

    with pytest.raises(CatalogNotFoundError) as exc:
        resolve_catalog_dir("goae_2030", catalogs_dir=tmp_path)

    assert CATALOG_FILENAME in str(exc.value)


def test_naming_both_an_edition_and_a_path_is_refused():
    """Two answers to "which catalog" is the ambiguity routing exists to remove."""
    with pytest.raises(CatalogError):
        load_catalog(load_catalog().path, catalog_version=CURRENT)


# ==========================================================================================
# 3. Test Cases A and B — the solver can only bill what the routed edition contains
# ==========================================================================================
#
# Two facts about this layer decide how these tests are written, and both are pre-existing
# engine behaviour rather than anything routing introduced:
#
#   * `app/bridge/entity_to_ziffer.py` holds a hard invariant — never propose a Ziffer the loaded
#     catalog does not contain — so a position outside the routed edition is dropped, with an
#     `unknown_ziffer` warning, before Soufflé or Clingo ever see it.
#   * `logic/asp/goae_optimize.lp:87` (`:- charged(Z), not code_info(Z, _, _).`) makes charging an
#     unknown position unsatisfiable rather than silently dropping it, described in that file as
#     belt and braces for exactly the injection this file is about.
#
# So the solver-level question is not "does Clingo reject Ziffer 20 in 1996" — it is "does the
# routed edition decide what Clingo is even told about", which is what `build_facts` answers.


def solver_for(version: str, settings, rules) -> ClingoSolver:
    return ClingoSolver(settings, load_catalog(catalog_version=version), rules)


def facts_for(version: str, *ziffern: str, settings, rules) -> str:
    """The injected Clingo facts for a set of confirmed positions, under one edition."""
    bridge = one_act_per_ziffer(*ziffern)
    rules_result = RulesResult(proposed=list(bridge.candidates), billable=list(ziffern))
    return solver_for(version, settings, rules).build_facts(
        rules_result, make_extraction(), bridge
    )


def solve_under(version: str, *ziffern: str, settings, rules):
    bridge = one_act_per_ziffer(*ziffern)
    rules_result = RulesResult(proposed=list(bridge.candidates), billable=list(ziffern))
    return solver_for(version, settings, rules).solve(
        rules_result, make_extraction(), bridge
    )


def test_the_routed_edition_decides_what_the_solver_is_told(settings, rules):
    """Test Case A at the solver boundary: the 1996 edition emits no catalog fact for Ziffer 20,
    so there is nothing for the ASP program to charge. An absent position is not a suppressed
    one — no rule fires, and none should."""
    old = facts_for(OLDEST, "5", "20", settings=settings, rules=rules)
    current = facts_for(CURRENT, "5", "20", settings=settings, rules=rules)

    assert 'code_info("20"' not in old
    assert 'code_info("5", 100,' in old, "Ziffer 5 at the 1996 rate"

    assert 'code_info("20"' in current
    assert 'code_info("5", 150,' in current, "and at the 2026 rate under the 2026 edition"


def test_the_novel_position_only_reaches_the_solver_from_the_edition_that_declares_it(
    settings, rules
):
    """99 exists in 2026 and 999 in the draft, so a position that is priced at all identifies the
    edition that priced it."""
    current = facts_for(CURRENT, "99", settings=settings, rules=rules)
    draft = facts_for(DRAFT, "99", settings=settings, rules=rules)

    assert 'code_info("99"' in current
    assert 'code_info("99"' not in draft
    assert 'code_info("999"' in facts_for(DRAFT, "999", settings=settings, rules=rules)
    assert 'code_info("999"' not in facts_for(CURRENT, "999", settings=settings, rules=rules)


def test_the_solver_bills_and_prices_ziffer_20_under_the_current_edition(settings, rules):
    """Test Case B. Both positions are in the 2026 edition, so both are charged and both get a
    § 5 factor decision — and the money is that edition's."""
    catalog = load_catalog(catalog_version=CURRENT)
    result = solve_under(CURRENT, "5", "20", settings=settings, rules=rules)

    assert result.solver_status == "SAT"
    assert {"5", "20"} <= set(result.billed)
    assert result.factor_for("20") is not None
    assert result.total_punkte == catalog.get("5").punkte + catalog.get("20").punkte


def test_the_same_position_is_priced_at_each_editions_rate(settings, rules):
    """Ziffer 5 alone through the real solver, so the only thing that can move the money is which
    catalog was routed to."""
    punkte = {
        version: solve_under(version, "5", settings=settings, rules=rules).total_punkte
        for version in ERAS
    }

    assert punkte == {v: spec["ziffer_5_punkte"] for v, spec in ERAS.items()}


def test_routing_has_to_happen_before_the_solver_not_inside_it(settings, rules):
    """Handing Clingo a confirmed position the routed edition does not contain is an error, and
    pinning that is the point: it is why the guard lives upstream.

    `logic/asp/goae_optimize.lp:87` refuses to charge a position with no catalog fact, so an
    injection that claimed Ziffer 20 is billable under 1996 is unsatisfiable rather than quietly
    reduced. Nothing in the engine produces that input — the bridge drops unknown Ziffern and the
    PADnext audit never reaches Clingo — but a future caller that routes an era *after* candidate
    selection would land here, and a loud failure is the right outcome.
    """
    with pytest.raises(ClingoError):
        solve_under(OLDEST, "5", "20", settings=settings, rules=rules)


# ==========================================================================================
# 4. Test Cases A and B through the PADnext audit — what a 2019 invoice actually gets told
# ==========================================================================================


def test_a_claimed_position_the_1996_edition_lacks_is_reported_as_unknown(rules, settings):
    """Test Case A, end to end. Refused, named, and kept out of the money — not silently dropped."""
    report = audit(INVOICE_5_AND_20, OLDEST, rules, settings)

    twenty = row(report, "20")
    assert twenty.verdict == "unknown_ziffer"
    assert twenty.in_catalog is False
    assert twenty.recomputed_amount_eur is None
    assert "1996" in twenty.reason or "goae_1996" in twenty.reason, (
        "the reason must name the catalog that lacks it, so the reader knows it is a temporal "
        f"verdict and not a typo: {twenty.reason!r}"
    )
    assert any(f.type == "padnext_unknown_ziffer" and f.ziffer == "20" for f in report.findings)

    # Its claimed euros are unpriceable, not defensible, and not silently absent from the totals.
    assert twenty.claimed_amount_eur == Decimal("24.13")
    assert report.unpriceable_claimed_eur == Decimal("24.13")
    assert report.recomputed_total_eur == row(report, "5").recomputed_amount_eur


def test_the_same_position_is_accepted_and_priced_under_the_current_edition(rules, settings):
    """Test Case B, end to end: same bytes, routed to 2026."""
    report = audit(INVOICE_5_AND_20, CURRENT, rules, settings)

    twenty = row(report, "20")
    assert twenty.verdict == "chargeable"
    assert twenty.in_catalog is True
    assert twenty.recomputed_amount_eur is not None and twenty.recomputed_amount_eur > 0
    assert twenty.punkte == load_catalog(catalog_version=CURRENT).get("20").punkte
    assert report.unpriceable_claimed_eur == Decimal("0.00")
    assert not any(f.type == "padnext_unknown_ziffer" for f in report.findings)


def test_one_invoice_is_worth_different_money_in_different_editions(rules, settings):
    """The reason routing exists at all: Ziffer 5 alone recomputes to three different amounts."""
    amounts = {
        version: audit(INVOICE_5_ONLY, version, rules, settings).recomputed_total_eur
        for version in ERAS
    }

    assert amounts[OLDEST] < amounts["goae_2012"] < amounts[CURRENT]
    assert amounts[CURRENT] == amounts[DRAFT]
    assert amounts[OLDEST] == Decimal("13.41"), "100 Punkte × 2.3 × 5.82873 ct, rounded half up"
    assert amounts[CURRENT] == Decimal("20.11"), "150 Punkte × 2.3 × 5.82873 ct"


# ==========================================================================================
# 5. Test Case C — the receipt hash separates the editions
# ==========================================================================================


def test_the_same_invoice_audited_under_two_editions_has_two_receipts(rules, settings):
    """Test Case C. Byte-identical input, and the receipts must not collide: a receipt that did
    would claim one audit answers for both fee schedules."""
    old = audit(INVOICE_5_AND_20, OLDEST, rules, settings)
    current = audit(INVOICE_5_AND_20, CURRENT, rules, settings)

    assert old.receipt_hash != current.receipt_hash
    assert old.catalog_version != current.catalog_version
    assert old.catalog_sha256 != current.catalog_sha256


def test_the_receipt_moves_even_when_the_two_editions_agree_on_every_number(rules, settings):
    """The sharper half of Test Case C.

    2026 and the draft price Ziffer 5 identically, so this invoice audits to exactly the same
    verdict and the same cent under both. The receipts still differ — because the receipt covers
    *which* catalog answered, not only what it answered. Without that, a practice could not tell an
    audit run against the draft from one run against the edition in force.
    """
    current = audit(INVOICE_5_ONLY, CURRENT, rules, settings)
    draft = audit(INVOICE_5_ONLY, DRAFT, rules, settings)

    assert current.recomputed_total_eur == draft.recomputed_total_eur
    assert [p.model_dump() for p in current.positions] == [p.model_dump() for p in draft.positions]
    assert current.receipt_hash != draft.receipt_hash


def test_re_auditing_one_invoice_against_one_edition_is_stable(rules, settings):
    """The other direction, and the reason the test above proves anything: nothing measured — no
    timing, no timestamp — is in the hash, so a difference can only come from the inputs."""
    first = audit(INVOICE_5_AND_20, CURRENT, rules, settings)
    second = audit(INVOICE_5_AND_20, CURRENT, rules, settings)

    assert first.receipt_hash == second.receipt_hash


def test_no_two_shipped_editions_share_an_identity():
    """What makes the receipt guarantee hold for editions this test file has never heard of.

    The receipt covers the *declared* version and the file digest, not the directory name. Two
    editions that agreed on both would produce one receipt hash for two different fee schedules —
    so a new edition copied from an old one without editing its `catalog_version` fails here.
    """
    catalogs = [load_catalog(catalog_version=v) for v in available_catalog_versions()]

    declared = [c.catalog_version for c in catalogs]
    digests = [c.sha256() for c in catalogs]

    assert len(set(declared)) == len(catalogs), f"duplicate catalog_version among {declared}"
    assert len(set(digests)) == len(catalogs), "two editions are byte-identical"
    assert all(c.catalog_version and c.catalog_version != "unknown" for c in catalogs)


def test_an_edition_records_both_where_we_looked_and_what_we_found(catalogs):
    """`routed_version` is the directory; `catalog_version` is the file's own claim. Keeping both
    is what makes a mislabelled edition directory detectable at all."""
    for version, catalog in catalogs.items():
        assert catalog.routed_version == version
        assert catalog.catalog_version != version, "the two are different claims, not aliases"
        assert version.removeprefix("goae_").split("_")[0] in catalog.catalog_version


# ==========================================================================================
# 6. the pipeline is bound to one edition
# ==========================================================================================


def test_a_pipeline_can_be_built_against_a_past_edition(settings):
    """Every downstream component — both solvers, the validator, the receipt — must see the same
    edition, so the route is taken once, at construction."""
    pipe = Pipeline(settings, catalog_version=OLDEST)

    assert pipe.catalog_edition == OLDEST
    assert pipe.catalog.is_synthetic
    assert not pipe.catalog.has("20")
    assert pipe.clingo.catalog is pipe.catalog
    assert pipe.validator.catalog is pipe.catalog
    assert pipe.souffle.catalog is pipe.catalog
    assert pipe._identity()["catalog_version"] == pipe.catalog.catalog_version


def test_a_pipeline_without_an_edition_still_loads_the_configured_catalog(settings):
    pipe = Pipeline(settings)

    assert pipe.catalog_edition == DEFAULT_CATALOG_VERSION
    assert pipe.catalog.path == settings.catalog_path


def test_a_pipeline_refuses_an_unknown_edition_at_construction(settings):
    """Not at first solve: a mis-typed era must fail before anything is billed."""
    with pytest.raises(CatalogNotFoundError):
        Pipeline(settings, catalog_version="goae_1800")


def test_a_pipeline_refuses_a_catalog_and_an_edition_together(settings):
    with pytest.raises(ValueError):
        Pipeline(settings, load_catalog(), catalog_version=CURRENT)


# ==========================================================================================
# 7. the fixtures are generated, not hand-maintained
# ==========================================================================================


def test_the_committed_fixtures_match_their_generator():
    """Four catalogs that must stay structurally identical are not something to edit by hand. If
    this fails, run `python scripts/make_temporal_fixtures.py`."""
    spec = importlib.util.spec_from_file_location(
        "make_temporal_fixtures", ENGINE_DIR / "scripts" / "make_temporal_fixtures.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    assert module.build(check=True) == 0
